package cn.xigua.childcare;
import java.time.*;
public final class CoreTest {
    static int n;
    static void equal(Object want,Object got){ n++; if(!want.equals(got))throw new AssertionError("Expected "+want+", got "+got); }
    static void bad(Runnable r){n++;try{r.run();}catch(IllegalArgumentException good){return;}throw new AssertionError("Invalid value accepted");}
    public static void main(String[] args){
        ZoneId zone=ZoneId.of("Asia/Shanghai");
        long[] day=CareRules.day(LocalDate.of(2026,10,2),zone);
        equal(86400000L,day[1]-day[0]);
        equal(3600000L,CareRules.overlap(day[0]-3600000,day[0]+3600000,day[0],day[1]));
        equal(0L,CareRules.overlap(day[1],day[1]+60000,day[0],day[1]));
        long[] dst=CareRules.day(LocalDate.of(2026,3,8),ZoneId.of("America/New_York"));
        equal(23*3600000L,dst[1]-dst[0]);
        bad(()->CareRules.validate("feeding",-1,1,0,""));
        bad(()->CareRules.validate("sleep",0,200,100,""));
        bad(()->CareRules.validate("sleep",0,100,100,""));
        bad(()->CareRules.validate("unknown",0,1,0,""));
        CareRules.validate("feeding",150,1,0,"formula");
        equal("\"'=SUM(A1)\"",CareRules.csv("=SUM(A1)"));
        equal("\"a\"\"b,c\"",CareRules.csv("a\"b,c"));
        RequestOwner owner=new RequestOwner();
        String qa=owner.begin("qa"), story=owner.begin("story");
        equal(true,owner.accepts("qa",qa));
        equal(false,owner.accepts("story",qa));
        owner.cancel("qa"); equal(false,owner.accepts("qa",qa));
        equal(true,owner.accepts("story",story));
        String newer=owner.begin("story");equal(false,owner.accepts("story",story));equal(true,owner.accepts("story",newer));
        equal(true,CareRules.sameOrigin("https://example.com/api", "https://example.com/media/a.mp3"));
        equal(false,CareRules.sameOrigin("https://example.com/api", "https://evil.com/a"));
        equal("feeding",CareRules.voiceKind("刚喂了150毫升配方奶"));
        equal(150.0,CareRules.voiceQuantity("刚喂了一百五十毫升母乳"));
        equal(99.5,CareRules.voiceQuantity("喂了九十九点五毫升"));
        equal(99.5,CareRules.voiceQuantity("喂了99.5ml"));
        equal(20.0,CareRules.voiceQuantity("二十毫升"));
        equal(150,CareRules.voiceAmount("刚喂了150毫升配方奶"));
        equal("diaper",CareRules.voiceKind("刚换了尿湿的尿布"));
        equal("",CareRules.voiceKind("今天天气好"));
        equal("\"'=SUM(A1)\nnext\"",CareRules.csv("=SUM(A1)\nnext"));
        equal(false,PlaybackRules.resumeCreatesPlayer("buffering",true));
        equal(false,PlaybackRules.resumeCreatesPlayer("buffering_paused",true));
        equal(false,PlaybackRules.resumeCreatesPlayer("playing",true));
        equal(true,PlaybackRules.resumeCreatesPlayer("stopped",false));
        bad(()->CareRules.validateAt("sleep",0,100,200,"",150));
        bad(()->CareRules.validateAt("feeding",150,200,0,"",150));
        bad(()->CareRules.validate("feeding",Double.NaN,1,0,""));
        bad(()->CareRules.validate("feeding",Double.POSITIVE_INFINITY,1,0,""));
        equal("99.5",CareRules.quantity(99.5));
        equal("150",CareRules.quantity(150));
        equal("record",IntentRouter.classify("记一下刚喂了150毫升母乳").action);
        equal("feeding",IntentRouter.classify("刚喝了99.5毫升奶").kind);
        equal("qa",IntentRouter.classify("宝宝喝多少奶合适？").action);
        equal("qa",IntentRouter.classify("宝宝睡不着怎么办").action);
        equal("story",IntentRouter.classify("讲个睡前故事").action);
        equal("audio",IntentRouter.classify("播放雨声").action);
        equal("sleep_end",IntentRouter.classify("宝宝醒了").action);
        equal("clarify",IntentRouter.classify("不要开始睡眠").action);
        equal("clarify",IntentRouter.classify("记喂奶然后讲一个故事").action);
        equal("clarify",IntentRouter.classify("明天喂奶150毫升").action);
        equal("qa",IntentRouter.classify("为什么故事能帮助入睡").action);
        equal("record",IntentRouter.classify("补记昨天睡了两小时").action);
        equal("record",IntentRouter.classify("昨天宝宝醒了").action);
        equal("clarify",IntentRouter.classify("喂了150毫升并换了尿布").action);
        equal("clarify",IntentRouter.classify("不播放雨声").action);
        equal("clarify",IntentRouter.classify("别播放雨声").action);
        equal("clarify",IntentRouter.classify("我不想播放雨声").action);
        equal("clarify",IntentRouter.classify("请先别播放雨声").action);
        equal("clarify",IntentRouter.classify("先记下喂了150毫升，再播放雨声").action);
        equal("clarify",IntentRouter.classify("播放雨声并讲一个故事").action);

        equal("records",IntentRouter.classify("今天喝了多少奶").action);
        equal("clarify",IntentRouter.classify("不用播放雨声").action);
        equal("clarify",IntentRouter.classify("不必播放雨声").action);
        equal("clarify",IntentRouter.classify("别给我播放雨声").action);
        equal("clarify",IntentRouter.classify("暂停播放并继续播放").action);
        equal("clarify",IntentRouter.classify("停止朗读并讲一个故事").action);
        equal("clarify",IntentRouter.classify("先检查版本，再播放雨声").action);
        FamilyRules.validateChild("西瓜", "2026-01-01", "Asia/Shanghai", LocalDate.of(2026,10,3));
        bad(()->FamilyRules.validateChild("", "", "Asia/Shanghai", LocalDate.now()));
        bad(()->FamilyRules.validateChild("西瓜", "2099-01-01", "Asia/Shanghai", LocalDate.now()));
        bad(()->FamilyRules.validateMember("妈妈", "照护者", "garbage"));
        FamilyRules.validateMember("妈妈", "妈妈", "");
        equal("爸爸",FamilyRules.validateCaregiverTitle(" 爸爸 "));
        equal("爷爷",FamilyRules.caregiverTitle("旧姓名"," 爷爷 "));
        equal("旧称谓",FamilyRules.caregiverTitle("旧称谓",""));
        bad(()->FamilyRules.validateCaregiverTitle("  "));
        bad(()->FamilyRules.validateCaregiverTitle("长".repeat(21)));
        UpdateRules.sameOrigin("https://EXAMPLE.com/feed", "https://example.com:443/app.apk");
        bad(()->UpdateRules.sameOrigin("https://a.example/feed", "https://b.example/app.apk"));
        bad(()->UpdateRules.sameOrigin("https://a.example/feed", "https://a.example:444/app.apk"));
        bad(()->UpdateRules.token("header\\r\\n".replace("\\r", "\r").replace("\\n", "\n")));
        bad(()->UpdateRules.token("x".repeat(2049)));
        UpdateRules.validate("cn.xigua.childcare",2,26,"https://example.com/app.apk","a".repeat(64),"cn.xigua.childcare",1,36);
        bad(()->UpdateRules.validate("other",2,26,"https://example.com/a.apk","a".repeat(64),"cn.xigua.childcare",1,36));
        bad(()->UpdateRules.validate("cn.xigua.childcare",1,26,"https://example.com/a.apk","a".repeat(64),"cn.xigua.childcare",1,36));
        bad(()->UpdateRules.validate("cn.xigua.childcare",2,37,"https://example.com/a.apk","a".repeat(64),"cn.xigua.childcare",1,36));
        bad(()->UpdateRules.validate("cn.xigua.childcare",2,26,"http://example.com/a.apk","a".repeat(64),"cn.xigua.childcare",1,36));
        bad(()->UpdateRules.validate("cn.xigua.childcare",2,26,"https://user:pass@example.com/a.apk","a".repeat(64),"cn.xigua.childcare",1,36));
        System.out.println("PASS "+n+" core assertions");
    }
}
