package cn.xigua.childcare;
import android.app.*;
import android.content.Context;
import android.os.Bundle;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

/** Tests only a separate named database and disposable local server. */
public final class StoreInstrumentation extends Instrumentation {
    private int assertions;private String dbName;private Store store;private Context target;private StringBuilder log=new StringBuilder();
    private void equal(Object expected,Object value){assertions++;if(!expected.equals(value))throw new AssertionError("Expected "+expected+" got "+value);}
    private boolean familyOnly;
    @Override public void onCreate(Bundle b){super.onCreate(b);familyOnly=b!=null&&"family".equals(b.getString("scope"));start();}
    @Override public void onStart(){Bundle result=new Bundle();target=getTargetContext();dbName="instrumentation-"+UUID.randomUUID()+".db";try{
        if(familyOnly){if(!(android.os.Build.FINGERPRINT.contains("generic")||android.os.Build.FINGERPRINT.contains("emulator")||android.os.Build.HARDWARE.equals("ranchu")))throw new IllegalStateException("Isolated emulator required");familyLifecycle();result.putString("stream","PASS "+assertions+" caregiver persistence assertions\n");finish(Activity.RESULT_OK,result);return;}
        connectionSnapshot();instanceFence();familyLifecycle();providerProfiles();requestIdentity();updateContinuity();voiceSubmitLifecycle();
        store=new Store(target,dbName);long now=System.currentTimeMillis();JSONObject feed=Store.obj("kind","feeding","start",now,"end",0,"amount",180,"detail","母乳","note","test");String id=store.save(feed);equal(1,store.pending());String op=store.outbox().get(0).optString("id");store.close();store=new Store(target,dbName);equal(op,store.outbox().get(0).optString("id"));equal(180,store.event(id).optInt("amount"));
        store.toggleSleep(now-3600000);equal(2,store.pending());equal(1,store.outbox().size());try{store.save(Store.obj("kind","sleep","start",now,"end",0,"amount",0));throw new AssertionError("A second active sleep replaced the first");}catch(IllegalArgumentException expected){}equal(now-3600000,store.activeSleep().optLong("start"));store.close();store=new Store(target,dbName);equal(now-3600000,store.activeSleep().optLong("start"));store.toggleSleep(now);equal(true,store.activeSleep()==null);
        JSONObject before=store.delete(id);equal(1,store.event(id).optInt("deleted"));long removedDelete=store.query("SELECT seq FROM outbox WHERE entity=? AND action='delete'",id).get(0).optLong("seq");store.undo(before);equal(0,store.event(id).optInt("deleted"));equal(0,store.query("SELECT seq FROM outbox WHERE entity=? AND action='delete'",id).size());equal(false,store.freeze(removedDelete,"{}"));
        int count=store.pending();try{store.save(Store.obj("kind","sleep","start",100,"end",99,"amount",0));throw new AssertionError("invalid saved");}catch(IllegalArgumentException expected){}equal(count,store.pending());
        log.append("Database/restart/sleep/delete undo: PASS\n");
        // Start a clean isolated database for the actual backend wire protocol.
        store.close();target.deleteDatabase(dbName);store=new Store(target,dbName);store.set("base_url","https://fixture.invalid");store.set("token","fixture-care");store.set("generation","1");
        SocketTransport transport=new SocketTransport();transport.call("POST","/fixture/reset",Store.obj(),"fixture-owner");Api api=new Api((CareApp)target.getApplicationContext(),store,transport);equal(true,api.sync());feed=Store.obj("kind","feeding","start",now,"end",0,"amount",180,"detail","母乳","note","fixture");id=store.save(feed);String operation=store.outbox().get(0).optString("id");transport.losePush=true;equal(false,api.sync());equal(1,store.pending());equal(operation,store.outbox().get(0).optString("id"));String frozen=store.outbox().get(0).optString("wire");equal(true,frozen.contains(operation));
        store.close();store=new Store(target,dbName);api=new Api((CareApp)target.getApplicationContext(),store,transport);equal(true,api.sync());equal(0,store.pending());equal(1L,store.event(id).optLong("revision"));equal(2,transport.pushes);equal(frozen,transport.lastWire);
        JSONObject stats=api.statistics(java.time.LocalDate.now(java.time.ZoneId.of("Asia/Shanghai")),java.time.ZoneId.of("Asia/Shanghai"));equal(1,stats.getJSONObject("childcare").getInt("feeding_count"));equal(180.0,stats.getJSONObject("childcare").getDouble("milk_ml"));log.append("Actual backend / lost receipt / restart / idempotency / statistics: PASS\n");
        JSONObject ours=store.event(id);ours.put("amount",220);store.save(ours);JSONObject remote=transport.call("GET","/records/"+id,null);JSONObject body=Store.obj("occurred_at",remote.get("occurred_at"),"timezone",remote.get("timezone"),"source",remote.get("source"),"data",remote.getJSONObject("data"),"media_ids",remote.get("media_ids"));body.getJSONObject("data").put("amount_ml",99.5);
        JSONObject webop=Store.obj("operation_id",UUID.randomUUID().toString(),"action","upsert","profile_id","baby","domain","childcare","entity_id",id,"generation",1,"base_revision",1,"record",body);transport.call("POST","/sync/push",Store.obj("client_id","fixture-web","operations",new JSONArray().put(webop)));equal(true,api.sync());equal(220,store.event(id).optInt("amount"));List<JSONObject> conflicts=store.query("SELECT * FROM outbox WHERE status='conflict'");equal(1,conflicts.size());api.resolve(conflicts.get(0),false);equal(99.5,store.event(id).optDouble("amount"));equal(0,store.pending());
        long[] fractionalDay=CareRules.day(java.time.LocalDate.now(java.time.ZoneId.of("Asia/Shanghai")),java.time.ZoneId.of("Asia/Shanghai"));equal(99.5,store.summary(fractionalDay[0],fractionalDay[1],now).optDouble("milk"));JSONObject fractional=store.event(id);fractional.put("note","fractional edit");store.save(fractional);equal(true,api.sync());equal(99.5,transport.call("GET","/records/"+id,null).getJSONObject("data").getDouble("amount_ml"));
        ours=store.event(id);ours.put("amount",200);store.save(ours);JSONObject clear=Store.obj("operation_id",UUID.randomUUID().toString(),"action","clear","profile_id","baby","generation",1);transport.call("POST","/sync/push",Store.obj("client_id","fixture-owner-client","operations",new JSONArray().put(clear)),"fixture-owner");equal(true,api.sync());equal("2",store.get("generation",""));conflicts=store.query("SELECT * FROM outbox WHERE status='conflict'");equal("generation_mismatch",conflicts.get(0).optString("error"));try{api.resolve(conflicts.get(0),true);throw new AssertionError("reset resurrected");}catch(IllegalArgumentException expected){}equal(1,store.pending());api.resolve(conflicts.get(0),false);equal(0,store.pending());equal(true,store.event(id)==null);log.append("Concurrent web edit / conflict / generation reset fence: PASS\n");
        String qa=UUID.randomUUID().toString(),story=UUID.randomUUID().toString();store.request(qa,"qa","QA fixture");store.request(story,"story","Story fixture");api.processJobs();Thread.sleep(1500);api.processJobs();equal("completed",store.requestById(qa).optString("status"));equal("completed",store.requestById(story).optString("status"));equal(true,store.requestById(qa).optString("response").contains("question"));equal(true,store.requestById(story).optString("response").contains("story"));store.cancelRequest(qa);store.requestState(qa,"completed",null,"late","none");equal("cancelled",store.requestById(qa).optString("status"));log.append("Actual backend Q&A/story ownership and cancellation: PASS\n");
        store.toggleSleep(now-60000);String activeId=store.activeSleep().optString("id");String legacy=UUID.randomUUID().toString();JSONObject legacyBody=Store.obj("occurred_at",null,"timezone","Asia/Shanghai","data",Store.obj("event_type","sleep","duration_seconds",600),"source",Store.obj("provider","legacy","source_id",null),"media_ids",new JSONArray());transport.call("POST","/sync/push",Store.obj("client_id","fixture-legacy","operations",new JSONArray().put(Store.obj("operation_id",UUID.randomUUID().toString(),"action","upsert","profile_id","baby","domain","childcare","entity_id",legacy,"generation",2,"base_revision",null,"record",legacyBody))));equal(true,api.sync());equal(activeId,store.activeSleep().optString("id"));equal(0,store.event(legacy).optInt("active"));equal(600000L,store.event(legacy).optLong("duration"));
        JSONObject unknown=Store.obj("kind","feeding","start",now,"end",0,"amount",0,"detail","母乳","note","");store.save(unknown);long[] day=CareRules.day(java.time.LocalDate.now(java.time.ZoneId.of("Asia/Shanghai")),java.time.ZoneId.of("Asia/Shanghai"));JSONObject totals=store.summary(day[0],day[1],now);equal(true,totals.isNull("milk"));equal(0L,totals.optLong("sleep_ms"));equal(60000L,totals.optLong("active_sleep_ms"));
        for(int k=0;k<102;k++)store.save(Store.obj("kind","diaper","start",now-k,"end",0,"amount",0,"detail","尿湿","note","pagination"));equal(100,store.timeline(day[0],day[1],0).size());equal(5,store.timeline(day[0],day[1],1).size());
        File isolated=new File(target.getCacheDir(),"disk-test-"+UUID.randomUUID());isolated.mkdirs();Context storage=new android.content.ContextWrapper(target){public File getFilesDir(){return isolated;}public File getCacheDir(){return isolated;}};File partial=new File(DiskMedia.dir(storage),"interrupted.part");try(FileOutputStream f=new FileOutputStream(partial)){f.write(new byte[4096]);}equal(4096L,DiskMedia.size(storage));DiskMedia.cleanup(storage);equal(0L,DiskMedia.size(storage));new File(isolated,"audio").delete();isolated.delete();log.append("Active/legacy sleep isolation, nullable statistics, claim guard, pagination and orphan cleanup: PASS\n");
        Api catalogApi=new Api((CareApp)target.getApplicationContext(),store,(method,path,payload)->{if(path.equals("/capabilities"))return Store.obj("protocol","personal-api-v1","instance_context_required",true,"server_instance_id",store.get("server_instance_id",""),"profiles",new JSONArray().put(Store.obj("id","baby","instance_id",store.get("profile_instance_id",""))),"audio_categories",new JSONArray().put("song").put("story"),"audio_formats",Store.obj("android",new JSONArray().put("audio/mpeg")));if(path.contains("category=story"))throw new IOException("isolated category failure");boolean second=path.contains("offset=100&");JSONArray items=new JSONArray();for(int k=second?100:0;k<(second?101:100);k++)items.put(Store.obj("id","catalog-"+k,"title",String.format(Locale.ROOT,"Track %03d",k),"mime_type","audio/mpeg","play_url","https://fixture.invalid/audio/"+k));return Store.obj("items",items,"offset",second?100:0,"next_offset",second?null:100,"total",101);});catalogApi.catalog("song");equal("100",store.get("catalog_next_song",""));equal(100,store.query("SELECT * FROM tracks").size());catalogApi.catalogMore("song");equal(101,store.query("SELECT * FROM tracks").size());equal("",store.get("catalog_next_song",""));equal(1,store.query("SELECT * FROM tracks ORDER BY title LIMIT 100 OFFSET 100").size());catalogApi.catalog("story");equal(101,store.query("SELECT * FROM tracks").size());log.append("Synthetic audio contract pages and independent category failure: PASS\n");
        microphoneBackground();longRecording();Activity visible=startActivitySync(new android.content.Intent(target,MainActivity.class).addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();File rain=DiskMedia.ambience(target);runOnMainSync(()->PlaybackService.play(target,"Audio focus test",rain.getAbsolutePath(),true));awaitPlayback("playing");
        android.media.AudioManager audio=target.getSystemService(android.media.AudioManager.class);android.media.AudioFocusRequest transientFocus=new android.media.AudioFocusRequest.Builder(android.media.AudioManager.AUDIOFOCUS_GAIN_TRANSIENT).setAudioAttributes(new android.media.AudioAttributes.Builder().setUsage(android.media.AudioAttributes.USAGE_MEDIA).setContentType(android.media.AudioAttributes.CONTENT_TYPE_SPEECH).build()).setOnAudioFocusChangeListener(change->{}).build();equal(android.media.AudioManager.AUDIOFOCUS_REQUEST_GRANTED,audio.requestAudioFocus(transientFocus));awaitPlayback("paused");audio.abandonAudioFocusRequest(transientFocus);awaitPlayback("playing");runOnMainSync(()->PlaybackService.control(target,"stop"));awaitPlayback("stopped");runOnMainSync(visible::finish);log.append("Platform playback and transient audio-focus pause/recovery/stop: PASS\n");
        result.putString("stream",log+"PASS "+assertions+" Android assertions\n");finish(Activity.RESULT_OK,result);
    }catch(Throwable e){result.putString("stream",log+"FAIL "+e+"\n"+Arrays.toString(e.getStackTrace()));finish(Activity.RESULT_CANCELED,result);}finally{if(store!=null)store.close();target.deleteDatabase(dbName);}}
    private void connectionSnapshot()throws Exception{
        String name="connection-"+UUID.randomUUID()+".db";Store f=new Store(target,name);try{
            f.configureBackup("https://a.fixture","a-fixture");Thread writer=new Thread(()->{for(int i=0;i<200;i++)f.configureBackup(i%2==0?"https://a.fixture":"https://b.fixture",i%2==0?"a-fixture":"b-fixture");});writer.start();
            java.lang.reflect.Field base=Api.class.getDeclaredField("base"),token=Api.class.getDeclaredField("token");base.setAccessible(true);token.setAccessible(true);
            for(int i=0;i<200;i++){Api a=new Api((CareApp)target.getApplicationContext(),f,(m,p,b)->Store.obj());String b=(String)base.get(a),t=(String)token.get(a);equal(true,b.equals("https://a.fixture")&&t.equals("a-fixture")||b.equals("https://b.fixture")&&t.equals("b-fixture"));}writer.join();
            String old=UUID.randomUUID().toString();f.request(old,"qa","legacy");f.set("request_transport_"+old,"");try{AiEngine.frozenProvider(f,old);throw new AssertionError("legacy request rebound");}catch(IOException expected){assertions++;}
            String direct=UUID.randomUUID().toString();f.set("request_provider_"+direct,"{\"id\":\"captured-service\"}");f.request(direct,"qa","frozen");equal("captured-service",AiEngine.frozenProvider(f,direct).optString("id"));
        }finally{f.close();target.deleteDatabase(name);}log.append("Atomic backup URL/token snapshots and missing-provider request rejection: PASS\n");
    }
    private void instanceFence()throws Exception{
        String name="instance-"+UUID.randomUUID()+".db";Store f=new Store(target,name);try{
            f.set("base_url","https://fixture.invalid");String server=UUID.randomUUID().toString(),profile=UUID.randomUUID().toString();final String[] active={server};final int[] pushes={0};
            Api a=new Api((CareApp)target.getApplicationContext(),f,(method,path,body)->{
                if(path.equals("/capabilities"))return Store.obj("protocol","personal-api-v1","instance_context_required",true,"server_instance_id",active[0],"profiles",new JSONArray().put(Store.obj("id","baby","instance_id",profile,"generation",1)));
                if(path.equals("/profiles"))return Store.obj("items",new JSONArray().put(Store.obj("id","baby","instance_id",profile,"generation",1)));
                if(path.startsWith("/sync/pull"))return Store.obj("through",0,"next_cursor",0,"changes",new JSONArray(),"has_more",false);
                if(path.equals("/sync/push")){pushes[0]++;JSONObject op=body.getJSONArray("operations").getJSONObject(0);equal(profile,op.optString("profile_instance_id"));return Store.obj("receipts",new JSONArray().put(Store.obj("operation_id",op.optString("operation_id"),"status","applied","revision",1)));}
                throw new IOException("unexpected fixture path");
            });
            // Existing local intent must not receive identities discovered later.
            String localId=f.save(Store.obj("kind","feeding","start",System.currentTimeMillis(),"amount",10));f.toggleSleep(System.currentTimeMillis()-10000);equal(true,a.sync());equal(0,pushes[0]);equal("instance_context_missing",f.query("SELECT error FROM outbox").get(0).optString("error"));
            f.toggleSleep(System.currentTimeMillis());equal("",Store.json(f.query("SELECT body FROM outbox ORDER BY seq DESC").get(0).optString("body")).getJSONObject("_sync_context").optString("server"));JSONObject oldEditor=f.timeline(0,System.currentTimeMillis()+1000).stream().filter(e->localId.equals(e.optString("id"))).findFirst().get();oldEditor.put("amount",11);f.save(oldEditor);equal("",Store.json(f.query("SELECT body FROM outbox ORDER BY seq DESC").get(0).optString("body")).getJSONObject("_sync_context").optString("server"));f.delete(localId);equal("",Store.json(f.query("SELECT body FROM outbox ORDER BY seq DESC").get(0).optString("body")).getJSONObject("_sync_context").optString("server"));
            JSONObject next=Store.obj("kind","feeding","start",System.currentTimeMillis(),"amount",20);f.save(next);equal(true,a.sync());equal(1,pushes[0]);
            String direct=UUID.randomUUID().toString();f.set("request_provider_"+direct,"{\"id\":\"user-service\"}");f.request(direct,"qa","direct ownership");equal(true,a.sync());equal("queued",f.requestById(direct).optString("status"));a.processJobs();equal("queued",f.requestById(direct).optString("status"));new Api((CareApp)target.getApplicationContext(),f,(m,p,b)->{throw new IOException("offline capabilities");}).processJobs();equal("queued",f.requestById(direct).optString("status"));
            JSONObject editor=Store.json(next.toString());active[0]=UUID.randomUUID().toString();equal(false,a.sync());equal(server,f.get("server_instance_id",""));equal(1,pushes[0]);
            editor.put("amount",30);f.save(editor);equal(false,a.sync());equal(1,pushes[0]);equal("instance_context_mismatch",f.query("SELECT error FROM outbox ORDER BY seq DESC").get(0).optString("error"));
        }finally{f.close();target.deleteDatabase(name);}log.append("Discovered instance context, unbound-queue quarantine and replacement-service/editor fence: PASS\n");
    }
    private void providerProfiles()throws Exception{
        String name="providers-"+UUID.randomUUID()+".db";Store f=new Store(target,name);try{
            Providers profiles=new Providers(target,f);JSONObject builtin=profiles.all().optJSONObject(0);equal(true,builtin.optString("base").contains("token-plan-cn"));equal(true,!builtin.optString("key").isEmpty());
            JSONObject second=Store.obj("id","second","name","Fixture","base","https://provider.example/v1","key","fixture-only","chat_model","chat-one","asr_model","speech-one","auth","bearer","asr_protocol","transcriptions");profiles.save(second);equal(2,profiles.all().length());profiles.select("chat","second");equal("second",profiles.selected("chat"));equal(builtin.optString("id"),profiles.selected("asr"));
            JSONObject original=profiles.resolve("chat"),snapshot=Providers.snapshot(original);long revision=original.optLong("revision");original.put("chat_model","chat-two");profiles.save(original);equal("chat-one",snapshot.optString("chat_model"));equal("chat-two",profiles.resolve("chat").optString("chat_model"));
            equal(false,profiles.models("second",revision,new JSONArray().put("stale"),"stale"));equal(true,profiles.models("second",revision+1,new JSONArray().put("available"),"ok"));
            f.close();f=new Store(target,name);profiles=new Providers(target,f);equal("second",profiles.selected("chat"));equal(1,profiles.get("second").optJSONArray("models").length());profiles.delete("second");equal(builtin.optString("id"),profiles.selected("chat"));profiles.delete(builtin.optString("id"));equal(0,profiles.all().length());
            f.close();f=new Store(target,name);profiles=new Providers(target,f);equal(0,profiles.all().length());try{profiles.resolve("asr");throw new AssertionError("missing speech profile accepted");}catch(IOException expected){assertions++;}
        }finally{f.close();target.deleteDatabase(name);}log.append("Multiple provider persistence, independent roles, frozen model and stale-discovery/delete fences: PASS\n");
    }
    private Object field(Activity a,String name)throws Exception{java.lang.reflect.Field f=MainActivity.class.getDeclaredField(name);f.setAccessible(true);return f.get(a);}
    private void injectVoice(Activity a,VoiceInput.BackendFactory factory)throws Exception{java.lang.reflect.Field f=MainActivity.class.getDeclaredField("voice");f.setAccessible(true);java.lang.reflect.Method nav=MainActivity.class.getDeclaredMethod("nav",String.class);nav.setAccessible(true);Object old=field(a,"composer");runOnMainSync(()->{try{f.set(a,new VoiceInput(a,factory));nav.invoke(a,"today");}catch(Exception e){throw new RuntimeException(e);}});long limit=android.os.SystemClock.elapsedRealtime()+7000;boolean[] fresh={false};while(!fresh[0]&&android.os.SystemClock.elapsedRealtime()<limit){runOnMainSync(()->{try{fresh[0]=field(a,"composer")!=old&&hasText(a.getWindow().getDecorView(),"说话");}catch(Exception e){throw new RuntimeException(e);}});if(!fresh[0])Thread.sleep(50);}if(!fresh[0])throw new AssertionError("Injected voice composer did not render");waitForIdleSync();}
    private boolean hasText(android.view.View view,String text){if(!view.isShown())return false;if(view instanceof android.widget.TextView&&text.contentEquals(((android.widget.TextView)view).getText()))return true;if(view instanceof android.view.ViewGroup){android.view.ViewGroup g=(android.view.ViewGroup)view;for(int i=0;i<g.getChildCount();i++)if(hasText(g.getChildAt(i),text))return true;}return false;}
    private void waitText(Activity a,String text)throws Exception{long limit=android.os.SystemClock.elapsedRealtime()+7000;boolean[] found={false};do{runOnMainSync(()->found[0]=hasText(a.getWindow().getDecorView(),text));if(found[0])return;Thread.sleep(50);}while(android.os.SystemClock.elapsedRealtime()<limit);throw new AssertionError("Missing UI state "+text);}
    private void waitFrames()throws Exception{long limit=android.os.SystemClock.elapsedRealtime()+4000;while(android.os.SystemClock.elapsedRealtime()<limit){File[] fs=target.getCacheDir().listFiles();if(fs!=null)for(File f:fs)if(f.getName().startsWith("capture-")&&f.length()>1644)return;Thread.sleep(50);}throw new AssertionError("Native microphone did not write frames");}
    private void waitForm(Activity a)throws Exception{long limit=android.os.SystemClock.elapsedRealtime()+7000;while(field(a,"formAmount")==null&&android.os.SystemClock.elapsedRealtime()<limit)Thread.sleep(50);equal(true,field(a,"formAmount")!=null);String[] amount={""};runOnMainSync(()->{try{amount[0]=((android.widget.EditText)field(a,"formAmount")).getText().toString();}catch(Exception e){throw new RuntimeException(e);}});equal("123",amount[0]);Dialog dialog=(Dialog)field(a,"sheet");equal(true,dialog.isShowing());runOnMainSync(()->((AlertDialog)dialog).getButton(-2).performClick());}
    private void voiceSubmitLifecycle()throws Exception{Activity a=startActivitySync(new android.content.Intent(target,MainActivity.class).addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();java.util.concurrent.CountDownLatch entered=new java.util.concurrent.CountDownLatch(1),release=new java.util.concurrent.CountDownLatch(1);java.util.concurrent.atomic.AtomicInteger calls=new java.util.concurrent.atomic.AtomicInteger();
        injectVoice(a,()->new SpeechBackend(){public void ready(){}public void cancel(){release.countDown();}public String transcribe(File wav,File scratch,MimoClient.Progress progress)throws Exception{calls.incrementAndGet();if(SpeechAudio.payloadBytes(wav)<1600)throw new IOException("no PCM");entered.countDown();if(!release.await(7,java.util.concurrent.TimeUnit.SECONDS))throw new IOException("fixture timeout");return "刚喂了123毫升母乳";}});
        runOnMainSync(()->clickText(a.getWindow().getDecorView(),"说话"));waitFrames();Object composer=field(a,"composer");java.lang.reflect.Method refresh=MainActivity.class.getDeclaredMethod("refresh");refresh.setAccessible(true);runOnMainSync(()->{try{refresh.invoke(a);}catch(Exception e){throw new RuntimeException(e);}});Thread.sleep(250);equal(true,composer==field(a,"composer"));waitText(a,"结束录音");
        runOnMainSync(()->clickText(a.getWindow().getDecorView(),"结束并发送"));equal(true,entered.await(4,java.util.concurrent.TimeUnit.SECONDS));waitText(a,"识别后发送");runOnMainSync(()->{clickText(a.getWindow().getDecorView(),"识别后发送");clickText(a.getWindow().getDecorView(),"识别后发送");});release.countDown();waitForm(a);equal(1,calls.get());equal(false,SpeechDrafts.exists(target));
        // Clear only the synthetic composer on the isolated emulator, never a real phone.
        runOnMainSync(()->{try{((android.widget.EditText)field(a,"prompt")).setText("");}catch(Exception e){throw new RuntimeException(e);}});
        java.util.concurrent.atomic.AtomicInteger attempt=new java.util.concurrent.atomic.AtomicInteger();injectVoice(a,()->new SpeechBackend(){public void ready(){}public void cancel(){}public String transcribe(File wav,File scratch,MimoClient.Progress progress)throws Exception{if(attempt.incrementAndGet()==1)throw new IOException("fixture network failure");return "刚喂了123毫升母乳";}});
        runOnMainSync(()->clickText(a.getWindow().getDecorView(),"说话"));waitFrames();runOnMainSync(()->clickText(a.getWindow().getDecorView(),"结束并发送"));waitText(a,"重试识别");equal(true,SpeechDrafts.exists(target));runOnMainSync(()->clickText(a.getWindow().getDecorView(),"重试识别"));waitText(a,"发送");equal(false,SpeechDrafts.exists(target));equal(true,field(a,"formAmount")==null);runOnMainSync(()->clickText(a.getWindow().getDecorView(),"发送"));waitForm(a);equal(2,attempt.get());runOnMainSync(a::finish);
        log.append("Real PCM + deferred Send, retained view, single submission and failed-audio retry/confirmation: PASS\n");
    }
    private void longRecording()throws Exception{Activity a=startActivitySync(new android.content.Intent(target,MainActivity.class).addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();waitText(a,"说话");runOnMainSync(()->clickText(a.getWindow().getDecorView(),"说话"));waitFrames();Object composer=field(a,"composer");Thread.sleep(65000);VoiceInput v=(VoiceInput)field(a,"voice");if(!v.active())throw new AssertionError("65-second microphone is no longer active");equal(true,v.active());waitText(a,"结束录音");if(composer!=field(a,"composer"))throw new AssertionError("65-second composer was replaced");equal(true,composer==field(a,"composer"));long bytes=0;File[] fs=target.getCacheDir().listFiles();if(fs!=null)for(File f:fs)if(f.getName().startsWith("capture-"))bytes=Math.max(bytes,f.length());if(bytes<=SpeechAudio.BYTES_PER_SECOND*60L)throw new AssertionError("65-second PCM payload too short: "+bytes);equal(true,bytes>SpeechAudio.BYTES_PER_SECOND*60L);runOnMainSync(()->clickText(a.getWindow().getDecorView(),"取消语音"));Thread.sleep(500);equal(false,v.active());equal(false,SpeechDrafts.exists(target));runOnMainSync(a::finish);log.append("Actual 65-second AudioRecord continues through minute refresh; cancel releases without ASR upload: PASS\n");}
    private void microphoneBackground()throws Exception{Activity visible=startActivitySync(new android.content.Intent(target,MainActivity.class).addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();runOnMainSync(()->clickText(visible.getWindow().getDecorView(),"说话"));java.lang.reflect.Field field=MainActivity.class.getDeclaredField("voice");field.setAccessible(true);VoiceInput voice=(VoiceInput)field.get(visible);equal(true,voice.active());long deadline=android.os.SystemClock.elapsedRealtime()+4000;boolean captured=false;while(android.os.SystemClock.elapsedRealtime()<deadline){File[] fs=target.getCacheDir().listFiles();if(fs!=null)for(File f:fs)if(f.getName().startsWith("capture-")&&f.length()>44)captured=true;if(captured)break;Thread.sleep(50);}equal(true,captured);runOnMainSync(()->visible.moveTaskToBack(true));deadline=android.os.SystemClock.elapsedRealtime()+4000;while(voice.active()&&android.os.SystemClock.elapsedRealtime()<deadline)Thread.sleep(50);equal(false,voice.active());Thread.sleep(400);int files=0;File[] fs=target.getCacheDir().listFiles();if(fs!=null)for(File f:fs)if(f.getName().startsWith("capture-"))files++;equal(0,files);runOnMainSync(visible::finish);log.append("Actual AudioRecord foreground capture, Home cancellation and temporary WAV cleanup: PASS\n");}
    private static boolean clickText(android.view.View view,String text){if(view instanceof android.widget.TextView&&text.contentEquals(((android.widget.TextView)view).getText())&&view.isClickable()){view.performClick();return true;}if(view instanceof android.view.ViewGroup){android.view.ViewGroup group=(android.view.ViewGroup)view;for(int k=0;k<group.getChildCount();k++)if(clickText(group.getChildAt(k),text))return true;}return false;}
    private void updateContinuity()throws Exception{equal(Updates.version(Updates.installed(target))+1,Updates.version(Updates.verify(target,new File("/data/local/tmp/xigua-update-candidate.apk"))));for(String file:new String[]{"/data/local/tmp/xigua-update-wrong.apk","/data/local/tmp/xigua-wrong-package.apk","/data/local/tmp/xigua-old-version.apk"}){assertions++;try{Updates.verify(target,new File(file));throw new AssertionError("invalid update accepted: "+file);}catch(IOException expected){}}
        String name="updates-"+UUID.randomUUID()+".db";Store f=new Store(target,name);try{CareApp app=(CareApp)target.getApplicationContext();java.util.concurrent.CountDownLatch entered=new java.util.concurrent.CountDownLatch(1),release=new java.util.concurrent.CountDownLatch(1);f.set("update_channel","https://a.example/release.json");java.util.concurrent.Future<?> old=app.network.submit(()->{entered.countDown();try{if(!release.await(5,java.util.concurrent.TimeUnit.SECONDS))throw new RuntimeException("test timeout");}catch(InterruptedException e){throw new RuntimeException(e);}f.set("update_release","old-channel-result");});if(!entered.await(5,java.util.concurrent.TimeUnit.SECONDS))throw new AssertionError("network busy");java.util.concurrent.Future<?> change=app.network.submit(()->Updates.setChannel(f,"https://b.example/release.json"));release.countDown();old.get(5,java.util.concurrent.TimeUnit.SECONDS);change.get(5,java.util.concurrent.TimeUnit.SECONDS);equal("https://b.example/release.json",f.get("update_channel",""));equal("",f.get("update_release",""));equal("",f.get("update_file",""));}finally{f.close();target.deleteDatabase(name);}log.append("Actual newer APK signer continuity; wrong signer/package/downgrade rejected; queued channel switch fence: PASS\n");}
    private void requestIdentity()throws Exception{String name="identity-"+UUID.randomUUID()+".db";Store f=new Store(target,name);try{for(String field:new String[]{"request_id","request_type","profile_id"}){String id=UUID.randomUUID().toString();f.request(id,"qa","ownership test");Api a=new Api((CareApp)target.getApplicationContext(),f,(method,path,body)->{if(path.equals("/capabilities"))return Store.obj("protocol","personal-api-v1","profiles",new JSONArray().put("baby"),"ai",Store.obj("enabled",true));JSONObject wrong=Store.obj("id","victim-job","request_id",id,"request_type","question","profile_id","baby","status","queued");wrong.put(field,"unrelated");return wrong;});a.processJobs();equal("failed",f.requestById(id).optString("status"));equal("",f.requestById(id).optString("job"));}String id=UUID.randomUUID().toString();f.request(id,"qa","claim");equal(true,f.claimRequest(id));equal(false,f.claimRequest(id));f.cancelRequest(id);f.requestState(id,"completed",null,"late","");equal("cancelled",f.requestById(id).optString("status"));}finally{f.close();target.deleteDatabase(name);}log.append("AI request mismatch cannot persist/cancel another job; atomic claim and late-result fence: PASS\n");}
    private void familyLifecycle() throws Exception {
        String name="family-"+UUID.randomUUID()+".db"; Store f=new Store(target,name);
        try {
            String mother=f.registerMember("妈妈","妈妈",""); String father=f.registerMember("爸爸","爸爸","");
            equal(mother,f.selectedMember().optString("id"));
            JSONObject e=Store.obj("kind","feeding","start",System.currentTimeMillis()-1000,"end",0,"amount",123,"detail","母乳","note","");String id=f.save(e);
            equal("妈妈",f.event(id).optString("caregiver_name"));
            f.updateMember(mother,"妈妈新称呼","妈妈","");f.selectMember(father);f.setMemberActive(mother,false);
            equal("妈妈",f.event(id).optString("caregiver_name")); equal(father,f.selectedMember().optString("id"));
            try{f.setMemberActive(father,false);throw new AssertionError("selected caregiver deactivated");}catch(IllegalArgumentException expected){}
            f.setMemberActive(mother,true); f.close();f=new Store(target,name);
            equal(2,f.members().size());equal(father,f.selectedMember().optString("id"));
            f.saveChild("西瓜新昵称","2026-01-01","Asia/Shanghai");equal("西瓜新昵称",f.get("child_name",""));
            try{f.saveChild("坏值","2099-01-01","invalid");throw new AssertionError("invalid child accepted");}catch(IllegalArgumentException expected){}
            equal("西瓜新昵称",f.get("child_name",""));
            String grandma=f.registerMember("旧姓名","奶奶","");f.selectMember(grandma);
            String named=f.save(Store.obj("kind","diaper","start",System.currentTimeMillis(),"detail","尿湿"));
            equal("奶奶",f.event(named).optString("caregiver_name"));
            f.updateMember(grandma,"外婆","外婆","");JSONObject same=f.event(named);same.put("note","keep historical attribution");f.save(same);
            equal("奶奶",f.event(named).optString("caregiver_name"));
            equal("妈妈",f.event(id).optString("caregiver_name"));
        } finally {f.close();target.deleteDatabase(name);}
        String old="migration-"+UUID.randomUUID()+".db";
        android.database.sqlite.SQLiteDatabase d=target.openOrCreateDatabase(old,0,null);
        d.execSQL("CREATE TABLE events(id TEXT PRIMARY KEY,kind TEXT,start INTEGER,end INTEGER,amount INTEGER,detail TEXT,note TEXT,timezone TEXT,revision INTEGER,deleted INTEGER,active INTEGER,duration INTEGER,remote_json TEXT)");
        d.execSQL("INSERT INTO events VALUES('legacy','feeding',1,0,150,'母乳','kept','Asia/Shanghai',0,0,0,0,'')");
        d.execSQL("CREATE TABLE outbox(seq INTEGER PRIMARY KEY,id TEXT,entity TEXT,action TEXT,body TEXT,generation INTEGER,wire TEXT,status TEXT,error TEXT,remote TEXT)");
        d.execSQL("INSERT INTO outbox VALUES(1,'stable-operation','legacy','upsert','{}',0,NULL,'pending','',NULL)");
        d.execSQL("CREATE TABLE meta(key TEXT PRIMARY KEY,value TEXT NOT NULL)");d.execSQL("INSERT INTO meta VALUES('child_name','原有宝宝')");
        d.setVersion(2);d.close();Store upgraded=new Store(target,old);
        try{equal(150,upgraded.event("legacy").optInt("amount"));equal("",upgraded.event("legacy").optString("caregiver_name"));equal("stable-operation",upgraded.outbox().get(0).optString("id"));equal("原有宝宝",upgraded.get("child_name",""));equal(3,upgraded.getReadableDatabase().getVersion());}finally{upgraded.close();target.deleteDatabase(old);}
        log.append("Caregiver registration/edit/select/deactivate/restart and populated schema2 migration: PASS\n");
    }
    private void awaitPlayback(String expected)throws InterruptedException{long deadline=android.os.SystemClock.elapsedRealtime()+7000;while(!expected.equals(PlaybackService.state)&&android.os.SystemClock.elapsedRealtime()<deadline)Thread.sleep(100);equal(expected,PlaybackService.state);}
    /** HTTP exists only in this test APK, to this disposable loopback fixture. */
    private static final class SocketTransport implements Api.Transport {
        boolean losePush;int pushes;String lastWire;String instance="",profile="";
        public JSONObject call(String method,String path,JSONObject body)throws IOException,JSONException{return call(method,path,body,"fixture-care");}
        public JSONObject contextual(String method,String path,JSONObject body,String expected)throws IOException,JSONException{return send(method,path,body,"fixture-care",expected);}
        JSONObject call(String method,String path,JSONObject body,String token)throws IOException,JSONException{
            if(body!=null&&path.equals("/sync/push")){JSONArray ops=body.getJSONArray("operations");for(int i=0;i<ops.length();i++)if(!ops.getJSONObject(i).has("profile_instance_id"))ops.getJSONObject(i).put("profile_instance_id",profile);}
            return send(method,path,body,token,instance);
        }
        JSONObject send(String method,String path,JSONObject body,String token,String expected)throws IOException,JSONException{
            byte[] payload=body==null?new byte[0]:body.toString().getBytes(StandardCharsets.UTF_8);try(Socket socket=new Socket("10.0.2.2",8912)){socket.setSoTimeout(10000);OutputStream out=socket.getOutputStream();out.write((method+" "+path+" HTTP/1.1\r\nHost: localhost\r\nAuthorization: Bearer "+token+"\r\n"+(expected.isEmpty()?"":"X-Personal-Instance-ID: "+expected+"\r\n")+"Content-Type: application/json\r\nConnection: close\r\nContent-Length: "+payload.length+"\r\n\r\n").getBytes(StandardCharsets.UTF_8));out.write(payload);out.flush();ByteArrayOutputStream bytes=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=socket.getInputStream().read(b))!=-1){bytes.write(b,0,n);if(bytes.size()>1024*1024)throw new IOException("large fixture response");}String response=bytes.toString("UTF-8");int split=response.indexOf("\r\n\r\n");if(split<0||!response.matches("(?s)^HTTP/1.[01] 2\\d\\d .*"))throw new IOException("fixture status "+response.substring(0,Math.min(80,response.length())));JSONObject json=new JSONObject(response.substring(split+4));if(path.equals("/capabilities")){instance=json.optString("server_instance_id");JSONArray profiles=json.optJSONArray("profiles");for(int i=0;profiles!=null&&i<profiles.length();i++){JSONObject p=profiles.optJSONObject(i);if(p!=null&&"baby".equals(p.optString("id")))profile=p.optString("instance_id");}}if("POST".equals(method)&&"/sync/push".equals(path)){pushes++;lastWire=body.getJSONArray("operations").getJSONObject(0).toString();if(losePush){losePush=false;throw new IOException("simulated lost response after server commit");}}return json;}
        }
    }
}
