package cn.xigua.childcare;
import android.app.*;import android.content.*;import android.os.Bundle;import android.view.*;import android.widget.*;import org.json.*;import java.time.*;import java.util.*;
/** The real native page reads a disposable Store; never touches the household DB. */
public final class TimelineUiInstrumentation extends Instrumentation {
    boolean night;int checks;void ok(boolean v,String message){checks++;if(!v)throw new AssertionError(message);}
    Object field(Object o,String key)throws Exception{java.lang.reflect.Field f=o.getClass().getDeclaredField(key);f.setAccessible(true);return f.get(o);}
    boolean click(View v,String label){if(v instanceof TextView&&label.contentEquals(((TextView)v).getText())&&v.isClickable()){v.performClick();return true;}if(v instanceof android.view.ViewGroup){android.view.ViewGroup g=(android.view.ViewGroup)v;for(int i=0;i<g.getChildCount();i++)if(click(g.getChildAt(i),label))return true;}return false;}
    String text(View v){String s=v instanceof TextView?((TextView)v).getText().toString()+"\n":"";if(v instanceof android.view.ViewGroup){android.view.ViewGroup g=(android.view.ViewGroup)v;for(int i=0;i<g.getChildCount();i++)s+=text(g.getChildAt(i));}return s;}
    View findText(View v,String wanted){if(v instanceof TextView&&wanted.contentEquals(((TextView)v).getText()))return v;if(v instanceof android.view.ViewGroup){android.view.ViewGroup g=(android.view.ViewGroup)v;for(int i=0;i<g.getChildCount();i++){View found=findText(g.getChildAt(i),wanted);if(found!=null)return found;}}return null;}
    void await(Activity a,String expected)throws Exception{long stop=android.os.SystemClock.elapsedRealtime()+8000;while(android.os.SystemClock.elapsedRealtime()<stop){final boolean[] found={false};runOnMainSync(()->found[0]=text(a.getWindow().getDecorView()).contains(expected));if(found[0])return;Thread.sleep(50);}throw new AssertionError("Missing "+expected);}
    @Override public void onCreate(Bundle b){super.onCreate(b);night=b!=null&&"true".equals(b.getString("night","false"));start();}
    @Override public void onStart(){Bundle result=new Bundle();Context context=getTargetContext();CareApp app=(CareApp)context.getApplicationContext();Store original=app.store;String name="timeline-ui-"+UUID.randomUUID()+".db";Store s=new Store(context,name);Activity current=null;try{
        if(!(android.os.Build.FINGERPRINT.contains("generic")||android.os.Build.FINGERPRINT.contains("emulator")||android.os.Build.HARDWARE.equals("ranchu")))throw new IllegalStateException("Isolated emulator required");
        app.database.submit(()->{}).get(5,java.util.concurrent.TimeUnit.SECONDS);app.store=s;String dad=s.registerMember("爸爸","爸爸",""),mom=s.registerMember("妈妈","妈妈","");long morning=LocalDate.now(ZoneId.of("Asia/Shanghai")).atTime(8,30).atZone(ZoneId.of("Asia/Shanghai")).toInstant().toEpochMilli();
        s.save(Store.obj("kind","feeding","start",morning,"amount",150,"detail","母乳"));s.save(Store.obj("kind","diaper","start",morning+40*60000,"detail","尿湿","caregiver_id",mom,"caregiver_name","妈妈"));
        current=startActivitySync(new Intent(context,MainActivity.class).putExtra("page","records").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));Activity activity=current;runOnMainSync(()->activity.getPreferences(0).edit().putBoolean("night",night).apply());await(activity,"喂奶 150 毫升");await(activity,"换尿布 · 尿湿");String screen=text(activity.getWindow().getDecorView());ok(screen.indexOf("08:30")<screen.indexOf("09:10"),"timeline order");ok(screen.contains("爸爸")&&screen.contains("妈妈"),"caregiver names");
        runOnMainSync(()->ok(click(activity.getWindow().getDecorView(),"记喂奶"),"direct feeding entry"));waitForIdleSync();Spinner actor=(Spinner)field(activity,"formCaregiver");int mother=-1;for(int i=0;i<actor.getCount();i++)if(actor.getItemAtPosition(i).toString().startsWith("妈妈"))mother=i;final int selected=mother;ok(selected>=0,"registered mother selectable");runOnMainSync(()->actor.setSelection(selected));
        ActivityMonitor monitor=addMonitor(MainActivity.class.getName(),null,false);runOnMainSync(activity::recreate);Activity restored=monitor.waitForActivityWithTimeout(8000);removeMonitor(monitor);ok(restored!=null,"activity recreated");current=restored;long deadline=android.os.SystemClock.elapsedRealtime()+8000;while(field(restored,"formCaregiver")==null&&android.os.SystemClock.elapsedRealtime()<deadline)Thread.sleep(50);waitForIdleSync();Spinner retained=(Spinner)field(restored,"formCaregiver");ok(retained!=null,"editor reopened after recreation");ok(retained.getSelectedItem().toString().startsWith("妈妈"),"caregiver draft survived recreation");
        runOnMainSync(()->{try{((EditText)field(restored,"formFrom")).setText(LocalDate.now(ZoneId.of("Asia/Shanghai"))+" 09:00");((EditText)field(restored,"formAmount")).setText("99.5");((AlertDialog)field(restored,"sheet")).getButton(-1).performClick();}catch(Exception e){throw new RuntimeException(e);}});
        await(restored,"喂奶 99.5 毫升");ok(s.timeline(morning-1,morning+2*3600000).size()==3,"saved actual page record");List<JSONObject> rows=s.query("SELECT * FROM events WHERE amount=99.5");ok(rows.size()==1&&"妈妈".equals(rows.get(0).optString("caregiver_name")),"selected caregiver persisted");
        String custom=s.save(Store.obj("kind","feeding","start",morning+90*60000,"amount",125,"detail","配方奶 A"));
        runOnMainSync(()->{try{java.lang.reflect.Method edit=MainActivity.class.getDeclaredMethod("edit",JSONObject.class,String.class);edit.setAccessible(true);edit.invoke(restored,s.event(custom),"feeding");}catch(Exception ex){throw new RuntimeException(ex);}});waitForIdleSync();Spinner ingredient=(Spinner)field(restored,"formDetail");ok("配方奶 A".equals(ingredient.getSelectedItem().toString()),"custom ingredient preserved by caregiver editor");runOnMainSync(()->{try{((AlertDialog)field(restored,"sheet")).getButton(-2).performClick();}catch(Exception ex){throw new RuntimeException(ex);}});waitForIdleSync();
        // Save real pixels before releasing the sandbox; a terminal snapshot alone cannot prove layout.
        runOnMainSync(()->{try{ScrollView sc=(ScrollView)field(restored,"scroll");View label=findText(sc,"这一天的时间线");sc.scrollTo(0,Math.max(0,label.getTop()-20));}catch(Exception ex){throw new RuntimeException(ex);}});getUiAutomation().waitForIdle(3500,6000);android.graphics.Bitmap bitmap=getUiAutomation().takeScreenshot();java.io.File screenshot=new java.io.File(context.getExternalFilesDir(null),night?"timeline-ui-night.png":"timeline-ui.png");try(java.io.FileOutputStream out=new java.io.FileOutputStream(screenshot)){bitmap.compress(android.graphics.Bitmap.CompressFormat.PNG,100,out);}bitmap.recycle();
        result.putString("stream","PASS "+checks+" native timeline/form/rotation assertions\n");finish(Activity.RESULT_OK,result);
    }catch(Throwable t){result.putString("stream","FAIL "+t+"\n"+Arrays.toString(t.getStackTrace()));finish(Activity.RESULT_CANCELED,result);}finally{if(current!=null){Activity a=current;runOnMainSync(a::finish);}app.database.submit(()->{});app.store=original;s.close();context.deleteDatabase(name);}}
}
