package cn.xigua.childcare;
import android.app.*;import android.content.*;import android.os.Bundle;import org.json.*;import java.util.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;
/** Only disposable databases and the local fixture; never run against phone data. */
public final class TimelineInstrumentation extends Instrumentation {
    java.util.List<String> failures=new java.util.ArrayList<>();int checks;void eq(Object a,Object b){checks++;if(!a.equals(b))throw new AssertionError(a+" != "+b);}
    @Override public void onCreate(Bundle b){super.onCreate(b);start();}
    @Override public void onStart(){Bundle result=new Bundle();Context c=getTargetContext();String db="timeline-"+UUID.randomUUID()+".db";Store s=new Store(c,db);try{
        s.configureBackup("https://fixture.invalid","fixture-care");Wire wire=new Wire();wire.call("POST","/fixture/reset",Store.obj(),"fixture-owner");Api api=new Api((CareApp)c.getApplicationContext(),s,wire);eq(true,api.sync());long now=System.currentTimeMillis()-60000;
        String dad=s.registerMember("爸爸","爸爸",""),mom=s.registerMember("妈妈","妈妈","");
        String first=s.save(Store.obj("kind","feeding","start",now,"amount",150,"detail","奶粉"));
        JSONObject change=s.event(first);change.put("_caregiver_changed",true);change.put("caregiver_id",mom);change.put("caregiver_name","妈妈");s.save(change);eq("妈妈",s.event(first).optString("caregiver_name"));
        s.updateMember(mom,"妈妈改名","妈妈","");change=s.event(first);change.put("note","edit after rename");s.save(change);eq("妈妈",s.event(first).optString("caregiver_name"));
        eq(true,api.sync());JSONObject remote=wire.call("GET","/records/"+first,null);eq("妈妈",remote.getJSONObject("data").getJSONObject("caregiver").getString("name"));eq(mom,remote.getJSONObject("data").getJSONObject("caregiver").getString("id"));
        // Server edit must be pulled even when the Android copy has another author.
        JSONObject body=Store.obj("occurred_at",remote.get("occurred_at"),"timezone","Asia/Shanghai","data",Store.obj("event_type","feeding","amount_ml",175,"caregiver",Store.obj("id",dad,"name","爸爸")));
        wire.call("POST","/sync/push",Store.obj("client_id","timeline-web","operations",new JSONArray().put(Store.obj("operation_id",UUID.randomUUID().toString(),"action","upsert","profile_id","baby","domain","childcare","entity_id",first,"generation",1,"base_revision",remote.get("revision"),"record",body))));
        eq(true,api.sync());eq("爸爸",s.event(first).optString("caregiver_name"));eq(175.0,s.event(first).optDouble("amount"));
        String second=s.save(Store.obj("kind","diaper","start",now+1000,"detail","大便","caregiver_id",mom,"caregiver_name","妈妈"));eq(true,api.sync());eq(first,s.timeline(now-1,now+10000).get(0).optString("id"));eq(second,s.timeline(now-1,now+10000).get(1).optString("id"));
        s.close();s=new Store(c,db);eq("爸爸",s.event(first).optString("caregiver_name"));eq("妈妈",s.event(second).optString("caregiver_name"));
        // A receipt frozen by v3 is replayed unchanged; attribution needs a new operation afterwards.
        Api currentApi=new Api((CareApp)c.getApplicationContext(),s,wire);java.lang.reflect.Method build=Api.class.getDeclaredMethod("record",JSONObject.class);build.setAccessible(true);
        String old=s.save(Store.obj("kind","feeding","start",now+2000,"amount",120));JSONObject queued=s.outbox().get(0),oldBody=(JSONObject)build.invoke(currentApi,s.event(old));oldBody.getJSONObject("data").remove("caregiver");JSONObject frozen=Store.obj("operation_id",queued.optString("id"),"action","upsert","profile_id","baby","profile_instance_id",s.get("profile_instance_id",""),"domain","childcare","entity_id",old,"generation",1,"base_revision",null,"record",oldBody);eq(true,s.freeze(queued.optLong("seq"),frozen.toString()));eq(true,currentApi.sync());eq("爸爸",s.event(old).optString("caregiver_name"));eq("爸爸",wire.call("GET","/records/"+old,null).getJSONObject("data").getJSONObject("caregiver").getString("name"));
        // A remote unknown diaper stays unknown through a caregiver-only edit.
        try{String undated=UUID.randomUUID().toString();JSONObject unknownBody=Store.obj("occurred_at",null,"timezone","Asia/Shanghai","data",Store.obj("event_type","diaper","diaper_kind",null,"caregiver",Store.obj("id",dad,"name","爸爸")));
        web(wire,undated,null,unknownBody);eq(true,currentApi.sync());eq("",s.event(undated).optString("detail"));JSONObject unknownEdit=s.event(undated);unknownEdit.put("_caregiver_changed",true);unknownEdit.put("caregiver_id",mom);unknownEdit.put("caregiver_name","妈妈");s.save(unknownEdit);eq(true,currentApi.sync());JSONObject unknownRemote=wire.call("GET","/records/"+undated,null);eq(true,unknownRemote.isNull("occurred_at"));eq(true,unknownRemote.getJSONObject("data").isNull("diaper_kind"));eq("妈妈",unknownRemote.getJSONObject("data").getJSONObject("caregiver").getString("name"));
        }catch(Throwable problem){failures.add("unknown diaper/time: "+problem);}
        // Keep-local conflict recovery must keep both a chosen name and an explicit clear.
        for(boolean clearActor:new boolean[]{false,true}){try{JSONObject before=s.event(first);before.put("_caregiver_changed",true);before.put("caregiver_id",clearActor?"":mom);before.put("caregiver_name",clearActor?"":"妈妈");s.save(before);JSONObject server=wire.call("GET","/records/"+first,null);JSONObject remoteBody=Store.obj("occurred_at",server.get("occurred_at"),"timezone","Asia/Shanghai","data",Store.obj("event_type","feeding","amount_ml",160,"ingredient","配方奶 A","caregiver",Store.obj("id",dad,"name","爸爸")));web(wire,first,server.optLong("revision"),remoteBody);eq(true,currentApi.sync());JSONObject conflict=s.query("SELECT * FROM outbox WHERE status='conflict'").get(0);currentApi.resolve(conflict,true);eq(clearActor?"":"妈妈",s.event(first).optString("caregiver_name"));eq(true,currentApi.sync());}catch(Throwable problem){failures.add("conflict "+clearActor+": "+problem);}}
        // A supplied sleep duration and occurrence may differ from its interval facts.
        try{String historical=UUID.randomUUID().toString();JSONObject sleepBody=Store.obj("occurred_at",null,"timezone","Asia/Shanghai","data",Store.obj("event_type","sleep","duration_seconds",2700));web(wire,historical,null,sleepBody);eq(true,currentApi.sync());JSONObject sleepEdit=s.event(historical);sleepEdit.put("_caregiver_changed",true);sleepEdit.put("caregiver_id",dad);sleepEdit.put("caregiver_name","爸爸");s.save(sleepEdit);eq(0,s.event(historical).optInt("active"));eq(true,currentApi.sync());eq(2700.0,wire.call("GET","/records/"+historical,null).getJSONObject("data").optDouble("duration_seconds"));
        }catch(Throwable problem){failures.add("historical sleep: "+problem);}
        if(!failures.isEmpty())throw new AssertionError(failures.toString());
        // Explicit remote null is unknown, not a license to reuse the selected member.
        java.lang.reflect.Method local=Api.class.getDeclaredMethod("local",JSONObject.class);local.setAccessible(true);remote.getJSONObject("data").put("caregiver",JSONObject.NULL);eq("",((JSONObject)local.invoke(new Api((CareApp)c.getApplicationContext(),s,wire),remote)).optString("caregiver_name"));
        // A named operation must remain pending when a service cannot retain attribution.
        s.set("capabilities","{}");java.lang.reflect.Method record=Api.class.getDeclaredMethod("record",JSONObject.class);record.setAccessible(true);try{record.invoke(new Api((CareApp)c.getApplicationContext(),s,wire),s.event(second));throw new AssertionError("named attribution silently dropped");}catch(java.lang.reflect.InvocationTargetException expected){eq(true,expected.getCause() instanceof IOException);}
        result.putString("stream","PASS "+checks+" caregiver timeline Android assertions\n");finish(Activity.RESULT_OK,result);
    }catch(Throwable t){result.putString("stream","FAIL "+t+"\n"+Arrays.toString(t.getStackTrace()));finish(Activity.RESULT_CANCELED,result);}finally{s.close();c.deleteDatabase(db);}}
    static void web(Wire wire,String id,Long revision,JSONObject record)throws Exception{JSONObject op=Store.obj("operation_id",UUID.randomUUID().toString(),"action","upsert","profile_id","baby","domain","childcare","entity_id",id,"generation",1,"base_revision",revision,"record",record);JSONObject receipt=wire.call("POST","/sync/push",Store.obj("client_id","timeline-review-web","operations",new JSONArray().put(op))).getJSONArray("receipts").getJSONObject(0);if(!"applied".equals(receipt.optString("status")))throw new AssertionError(receipt.toString());}
    static final class Wire implements Api.Transport {
        boolean losePush;int pushes;String lastWire;String instance="",profile="";
        public JSONObject call(String method,String path,JSONObject body)throws IOException,JSONException{return call(method,path,body,"fixture-care");}
        public JSONObject contextual(String method,String path,JSONObject body,String expected)throws IOException,JSONException{return send(method,path,body,"fixture-care",expected);}
        JSONObject call(String method,String path,JSONObject body,String token)throws IOException,JSONException{
            if(body!=null&&path.equals("/sync/push")){JSONArray ops=body.getJSONArray("operations");for(int i=0;i<ops.length();i++)if(!ops.getJSONObject(i).has("profile_instance_id"))ops.getJSONObject(i).put("profile_instance_id",profile);}
            return send(method,path,body,token,instance);
        }
        JSONObject send(String method,String path,JSONObject body,String token,String expected)throws IOException,JSONException{
            byte[] payload=body==null?new byte[0]:body.toString().getBytes(StandardCharsets.UTF_8);try(Socket socket=new Socket("10.0.2.2",8912)){socket.setSoTimeout(10000);OutputStream out=socket.getOutputStream();out.write((method+" "+path+" HTTP/1.1\r\nHost: localhost\r\nAuthorization: Bearer "+token+"\r\n"+(expected.isEmpty()?"":"X-Personal-Instance-ID: "+expected+"\r\n")+"Content-Type: application/json\r\nConnection: close\r\nContent-Length: "+payload.length+"\r\n\r\n").getBytes(StandardCharsets.UTF_8));out.write(payload);out.flush();ByteArrayOutputStream bytes=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=socket.getInputStream().read(b))!=-1){bytes.write(b,0,n);if(bytes.size()>1024*1024)throw new IOException("large fixture response");}String response=bytes.toString("UTF-8");int split=response.indexOf("\r\n\r\n");if(split<0||!response.matches("(?s)^HTTP/1.[01] 2\\d\\d .*"))throw new IOException("fixture status "+response.substring(0,Math.min(80,response.length())));JSONObject json=new JSONObject(response.substring(split+4));if(path.equals("/capabilities")){instance=json.optString("server_instance_id");JSONArray profiles=json.optJSONArray("profiles");for(int i=0;profiles!=null&&i<profiles.length();i++){JSONObject p=profiles.optJSONObject(i);if(p!=null&&"baby".equals(p.optString("id")))profile=p.optString("instance_id");}}if("POST".equals(method)&&"/sync/push".equals(path)){pushes++;lastWire=body.getJSONArray("operations").getJSONObject(0).toString();if(losePush){losePush=false;throw new IOException("simulated lost response after server commit");}}return json;}
        }
    }
}
