package cn.xigua.childcare;
import android.app.*;import android.content.*;import android.os.Bundle;import org.json.*;import java.io.*;import java.net.*;import java.security.*;import java.security.cert.*;import javax.net.ssl.*;import java.util.*;import java.util.concurrent.*;
/** One real local HTTPS download and Android installer upgrade, restricted to emulator fixtures. */
public final class UpdateInstallInstrumentation extends Instrumentation {
 String phase="prepare";@Override public void onCreate(Bundle b){super.onCreate(b);phase=b.getString("phase","prepare");start();}
 @Override public void onStart(){Bundle out=new Bundle();Context c=getTargetContext();CareApp app=(CareApp)c.getApplicationContext();Updates.Transport saved=Updates.transport;Activity visible=null;try{
  if(!android.os.Build.FINGERPRINT.contains("generic")&&!android.os.Build.MODEL.contains("sdk"))throw new AssertionError("Emulator fixture only");
  visible=startActivitySync(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();app.database.submit(()->{}).get(40,TimeUnit.SECONDS);app.network.submit(()->{}).get(40,TimeUnit.SECONDS);Store s=app.store;
  if(phase.equals("verify")){JSONObject receipt=Store.json(s.get("ota_fixture_receipt",""));if(Updates.version(Updates.installed(c))!=receipt.getLong("version"))throw new AssertionError("Android installation incomplete");JSONObject event=s.event(receipt.getString("event"));if(event==null||event.optInt("amount")!=147||!receipt.getString("caregiver").equals(event.optString("caregiver_id")))throw new AssertionError("Care record lost during upgrade");if(!receipt.getString("child").equals(s.get("child_name",""))||!receipt.getString("providers_hash").equals(hash(s.get("providers","").getBytes("UTF-8"))))throw new AssertionError("Profile or provider settings changed");boolean pending=false;for(JSONObject op:s.query("SELECT id FROM outbox WHERE id=?",receipt.getString("operation")))pending=true;if(!pending)throw new AssertionError("Pending intent lost during upgrade");if(!s.get("update_file","").isEmpty())throw new AssertionError("Installed candidate not cleaned");out.putString("stream","PASS real HTTPS download / Android installer / same signer / record-caregiver-profile-provider-outbox continuity / installed-candidate cleanup\n");}
  else{CertificateFactory cf=CertificateFactory.getInstance("X.509");java.security.cert.Certificate certificate;try(InputStream in=new FileInputStream("/data/local/tmp/xigua-update-fixture-cert.pem")){certificate=cf.generateCertificate(in);}KeyStore trust=KeyStore.getInstance(KeyStore.getDefaultType());trust.load(null,null);trust.setCertificateEntry("local-fixture",certificate);TrustManagerFactory tm=TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());tm.init(trust);SSLContext ssl=SSLContext.getInstance("TLS");ssl.init(null,tm.getTrustManagers(),null);Updates.transport=url->{HttpsURLConnection connection=(HttpsURLConnection)new URL(url).openConnection();connection.setSSLSocketFactory(ssl.getSocketFactory());return connection;};
   String member=s.registerMember("OTA-"+UUID.randomUUID().toString().substring(0,8),"爸爸","");s.selectMember(member);String event=s.save(Store.obj("kind","feeding","start",System.currentTimeMillis(),"amount",147,"detail","奶粉"));String operation="";for(JSONObject op:s.query("SELECT id FROM outbox WHERE entity=?",event))operation=op.optString("id");if(operation.isEmpty())throw new AssertionError("Missing fixture operation");
   Updates.configure(s,"https://127.0.0.1:8917/channel/latest.json","synthetic-downloader-"+String.join("",Collections.nCopies(32,"r")),true);s.set("update_automatic","0");Updates.checkChannel(app);JSONObject release=Store.json(s.get("update_release",""));if(release.optLong("version_code")!=6)throw new AssertionError("Local HTTPS newer manifest missing");Updates.download(app);if(s.get("update_file","").isEmpty())throw new AssertionError("Local HTTPS staging failed");s.set("ota_fixture_receipt",Store.obj("version",6,"event",event,"caregiver",member,"operation",operation,"child",s.get("child_name",""),"providers_hash",hash(s.get("providers","").getBytes("UTF-8"))).toString());final Activity activity=visible;final Exception[] problem={null};runOnMainSync(()->{try{Updates.install(activity);}catch(Exception e){problem[0]=e;}});if(problem[0]!=null)throw problem[0];out.putString("stream","PASS local HTTPS newer APK verified and Android installer opened; awaiting explicit fixture installation\n");}
  finish(Activity.RESULT_OK,out);
 }catch(Throwable t){out.putString("stream","FAIL "+t+"\n"+Arrays.toString(t.getStackTrace()));finish(Activity.RESULT_CANCELED,out);}finally{Updates.transport=saved;}}
 static String hash(byte[] value)throws Exception{StringBuilder b=new StringBuilder();for(byte v:MessageDigest.getInstance("SHA-256").digest(value))b.append(String.format(Locale.ROOT,"%02x",v&255));return b.toString();}
}
