package cn.xigua.childcare;
import android.app.*;import android.content.*;import android.content.pm.PackageInfo;import android.os.Bundle;import org.json.*;import java.io.*;import java.net.*;import java.util.*;import java.util.concurrent.*;
/** Disposable emulator database and injected HTTPS transport; SDK parses real signed APKs. */
public final class UpdateInstrumentation extends Instrumentation {
 int assertions;void eq(Object expected,Object actual){assertions++;if(!expected.equals(actual))throw new AssertionError(expected+" != "+actual);}
 @Override public void onCreate(Bundle b){super.onCreate(b);start();}
 static final String FEED="https://update.fixture/channel/latest.json",TOKEN="fixture-read-token";
 @Override public void onStart(){Bundle result=new Bundle();Context context=getTargetContext();CareApp app=(CareApp)context.getApplicationContext();String db="cloud-update-"+UUID.randomUUID()+".db";Store original=null,s=null;Updates.Transport saved=Updates.transport;Activity visible=null;try{
  if(!android.os.Build.FINGERPRINT.contains("generic")&&!android.os.Build.MODEL.contains("sdk"))throw new AssertionError("Emulator-only destructive fixtures");
  Activity warm=startActivitySync(new Intent(context,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();runOnMainSync(warm::finish);
  app.database.submit(()->{}).get(40,TimeUnit.SECONDS);app.network.submit(()->{}).get(40,TimeUnit.SECONDS);
  original=app.store;s=new Store(context,db);app.store=s;final Store isolated=s;
  String caregiver=s.registerMember("爸爸","爸爸","");String event=s.save(Store.obj("kind","feeding","start",System.currentTimeMillis(),"amount",150,"detail","奶粉"));s.set("providers","[{\"id\":\"configured\"}]");s.set("child_name","保持宝宝资料");s.set("update_channel","");Updates.initialize(app);
  eq(true,!s.get("update_channel","").isEmpty());eq(true,s.get("update_channel","").contains("/android-updates/"));eq(true,s.get("update_fallback","").contains("/cloud-backup/android-childcare-updates/"));eq(true,!s.get("update_token","").isEmpty());eq("1",s.get("update_automatic",""));eq("[{\"id\":\"configured\"}]",s.get("providers",""));eq("保持宝宝资料",s.get("child_name",""));eq(caregiver,s.event(event).optString("caregiver_id"));
  Updates.configure(s,"","",true);Updates.initialize(app);eq("",s.get("update_channel",""));s.set("update_epoch","corrupt legacy value");Updates.configure(s,FEED,TOKEN,true);eq(1L,Updates.channel(s).epoch);
  byte[] candidate=read(new File("/data/local/tmp/xigua-update-candidate.apk"));PackageInfo info=Updates.verify(app,new File("/data/local/tmp/xigua-update-candidate.apk"));long current=Updates.version(Updates.installed(app));JSONObject release=release(info,candidate);Wire wire=new Wire();Updates.transport=wire;wire.body=release.toString().getBytes("UTF-8");Updates.checkChannel(app);
  eq("Bearer "+TOKEN,wire.last.getRequestProperty("Authorization"));eq(false,wire.last.getInstanceFollowRedirects());eq(Updates.version(info),Store.json(s.get("update_release","")).optLong("version_code"));eq(true,s.get("update_status","").startsWith("发现新版本"));
  wire.body=candidate;Updates.download(app);eq("Bearer "+TOKEN,wire.last.getRequestProperty("Authorization"));eq(true,new File(Updates.dir(app),s.get("update_file","")).isFile());eq(Updates.version(info),Store.json(s.get("update_candidate","")).optLong("version_code"));eq(true,s.get("update_status","").contains("等待你确认安装"));eq(false,new File(Updates.dir(app),"download.part").exists());String staged=s.get("update_file","");
  Updates.cleanup(app);eq(staged,s.get("update_file",""));
  // A matching URL with a damaged body must never replace the previously verified candidate.
  wire.body=new byte[]{1,2,3};Updates.download(app);eq(staged,s.get("update_file",""));eq(true,s.get("update_status","").contains("校验失败"));eq(false,new File(Updates.dir(app),"download.part").exists());
  byte[] wrong=read(new File("/data/local/tmp/xigua-update-wrong.apk"));JSONObject invalid=release(info,wrong);s.set("update_release",invalid.toString());wire.body=wrong;Updates.download(app);eq(staged,s.get("update_file",""));eq(true,s.get("update_status","").contains("签名不匹配"));
  s.set("update_release",release.toString());wire.body=candidate;wire.onRead=()->Updates.cancel(app);Updates.download(app);wire.onRead=null;eq(true,s.get("update_status","").contains("已取消"));eq(false,new File(Updates.dir(app),"download.part").exists());
  // A metadata claim must equal the SDK-parsed actual package version.
  JSONObject lies=new JSONObject(release.toString());lies.put("version_code",Updates.version(info)+1);s.set("update_release",lies.toString());Updates.download(app);eq(true,s.get("update_status","").contains("版本与频道不符"));
  JSONObject cross=new JSONObject(release.toString());cross.put("apk_url","https://other.fixture/app.apk");wire.body=cross.toString().getBytes("UTF-8");int before=wire.requests;Updates.checkChannel(app);eq(before+1,wire.requests);eq("",s.get("update_release",""));eq(true,s.get("update_status","").contains("同一更新站点"));
  wire.body=release.toString().getBytes("UTF-8");wire.onRead=()->Updates.configure(isolated,"https://new.fixture/latest.json","new-token",true);Updates.checkChannel(app);wire.onRead=null;eq("https://new.fixture/latest.json",s.get("update_channel",""));eq("",s.get("update_release",""));eq(true,s.get("update_status","").contains("已接入云端"));
  // A transition channel tries the independent manifest first, then the legacy path and records the source.
  String primary="https://update.fixture/android-updates/latest.json",legacy="https://update.fixture/cloud-backup/android-childcare-updates/latest.json";Updates.configureWithFallback(s,primary,TOKEN,legacy,true);s.set("update_fallback_token","legacy-fixture-token");wire.perCode.put(primary,404);wire.perBody.put(legacy,release.toString().getBytes("UTF-8"));Updates.checkChannel(app);eq("legacy",s.get("update_source",""));eq(true,s.get("update_status","").startsWith("发现新版本"));wire.body=candidate;Updates.download(app);eq("Bearer legacy-fixture-token",wire.last.getRequestProperty("Authorization"));eq(true,new File(Updates.dir(app),s.get("update_file","")).isFile());s.set("update_file","");s.set("update_candidate","");for(File f:Objects.requireNonNull(Updates.dir(app).listFiles()))if(f.getName().startsWith("candidate-"))f.delete();
  Updates.configure(s,FEED,TOKEN,true);JSONObject installed=new JSONObject(release.toString());installed.put("version_code",current);wire.body=installed.toString().getBytes("UTF-8");Updates.checkChannel(app);eq("",s.get("update_release",""));eq(true,s.get("update_status","").startsWith("已是最新版本"));
  wire.code=401;Updates.checkChannel(app);eq(true,s.get("update_status","").contains("验证未通过"));wire.code=302;Updates.checkChannel(app);eq(true,s.get("update_status","").contains("不可用"));wire.code=200;wire.body=new byte[65537];Updates.checkChannel(app);eq(true,s.get("update_status","").contains("清单过大"));
  wire.body=release.toString().getBytes("UTF-8");s.set("update_automatic","1");s.set("update_last_attempt","0");before=wire.requests;for(int i=0;i<20;i++)Updates.maybeCheck(app);app.network.submit(()->{}).get(10,TimeUnit.SECONDS);eq(before+1,wire.requests);Updates.maybeCheck(app);app.network.submit(()->{}).get(10,TimeUnit.SECONDS);eq(before+1,wire.requests);
  // Changing cached APK bytes between preparation and installation is detected before Android launch.
  wire.body=candidate;Updates.download(app);File cached=new File(Updates.dir(app),s.get("update_file",""));try(FileOutputStream out=new FileOutputStream(cached,true)){out.write(1);}visible=startActivitySync(new Intent(context,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();final Activity activity=visible;final String[] problem={""};runOnMainSync(()->{try{Updates.install(activity);}catch(Exception e){problem[0]=e.getMessage();}});eq(true,problem[0].contains("已变化"));
  s.set("update_candidate",Store.obj("version_code",current).toString());Updates.cleanup(app);eq("",s.get("update_file",""));eq("",s.get("update_candidate",""));eq(false,cached.exists());eq(150,s.event(event).optInt("amount"));eq("保持宝宝资料",s.get("child_name",""));
  result.putString("stream","PASS "+assertions+" cloud update Android assertions\n");finish(Activity.RESULT_OK,result);
 }catch(Throwable t){result.putString("stream","FAIL "+t+"\n"+Arrays.toString(t.getStackTrace()));finish(Activity.RESULT_CANCELED,result);}finally{if(visible!=null){final Activity end=visible;runOnMainSync(end::finish);}Updates.transport=saved;Updates.busy.set(false);Updates.queued.set(false);if(original!=null)app.store=original;if(s!=null)s.close();context.deleteDatabase(db);}}
 static JSONObject release(PackageInfo p,byte[] apk)throws Exception{return Store.obj("package_name",p.packageName,"version_code",Updates.version(p),"version_name",p.versionName,"min_sdk",p.applicationInfo.minSdkVersion,"apk_url","https://update.fixture/channel/apks/fixture.apk","sha256",hash(apk),"size_bytes",apk.length,"notes","云端更新测试");}
 static String hash(byte[] b)throws Exception{byte[] h=java.security.MessageDigest.getInstance("SHA-256").digest(b);StringBuilder s=new StringBuilder();for(byte v:h)s.append(String.format(Locale.ROOT,"%02x",v&255));return s.toString();}
 static byte[] read(File f)throws Exception{try(InputStream in=new FileInputStream(f);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[32768];int n;while((n=in.read(b))!=-1)out.write(b,0,n);return out.toByteArray();}}
 static final class Wire implements Updates.Transport {byte[] body=new byte[0];int code=200,requests;Runnable onRead;HttpURLConnection last;final Map<String,Integer> perCode=new HashMap<>();final Map<String,byte[]> perBody=new HashMap<>();
  public HttpURLConnection open(String u)throws IOException{requests++;final byte[] raw=perBody.containsKey(u)?perBody.get(u):body;final int status=perCode.containsKey(u)?perCode.get(u):code;final Runnable hook=onRead;last=new HttpURLConnection(new URL(u)){public void connect(){}public void disconnect(){}public boolean usingProxy(){return false;}public int getResponseCode(){return status;}public long getContentLengthLong(){return raw.length;}public InputStream getInputStream(){if(hook!=null)hook.run();return new ByteArrayInputStream(raw);}};return last;}
 }
}
