idf_component_register(
    SRCS "main.c"
         "xigua/xigua_app.c"
         "xigua/xigua_core.c"
         "xigua/xigua_calendar.c"
         "xigua/xigua_export.c"
         "xigua/xigua_sound.c"
         "xigua/xigua_audio_policy.c"
         "xigua/xigua_audio.c"
         "xigua/xigua_input.c"
         "xigua/xigua_store.c"
         "xigua/xigua_ui.c"
         "xigua/xigua_keyboard.c"
         "xigua/xigua_config.c"
         "xigua/xigua_management.c"
         "xigua/xigua_json.c"
         "xigua/xigua_service.c"
         "xigua/xigua_network.c"
         "xigua/xigua_wifi_policy.c"
         "xigua/xigua_ai.c"
         "xigua/xigua_ai_protocol.c"
         "../assets/fonts/xigua_font_16.c"
    INCLUDE_DIRS "." "xigua"
    REQUIRES bsp esp_timer nvs_flash esp_wifi esp_event esp_netif
             json esp-tls http_parser mbedtls esp_driver_usb_serial_jtag lwip
)
