package cn.xigua.childcare;
import android.app.Activity;
import android.text.*;
import android.view.View;
import android.widget.*;
import java.util.function.Consumer;

/** One retained view and submission state, rather than separately wired recording/send buttons. */
final class CareComposer {
 final LinearLayout view;final EditText input;private final TextView status,cancel,retry;private final View mic,send;private final LinearLayout extras;private final SpeechSession session=new SpeechSession();private final VoiceInput voice;private final Consumer<String> route,draft;private String beforeVoice="";private boolean large;
 CareComposer(Activity a,Ui u,VoiceInput voice,String initial,boolean large,Consumer<String> draft,Consumer<String> route){this.voice=voice;this.route=route;this.draft=draft;this.large=large;view=u.column();view.setPadding(u.dp(8),u.dp(8),u.dp(8),u.dp(8));view.setBackgroundColor(u.surface);LinearLayout row=u.row();mic=u.iconAction("mic","说话",this::mic);row.addView(mic,new LinearLayout.LayoutParams(u.dp(48),u.dp(48)));input=u.input("说说刚发生的事…",initial,InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);input.setMinHeight(u.dp(48));input.setPadding(u.dp(10),u.dp(6),u.dp(10),u.dp(6));input.setMinLines(1);input.setMaxLines(3);input.setFilters(new InputFilter[]{new InputFilter.LengthFilter(12000)});row.addView(input,new LinearLayout.LayoutParams(0,-2,1));send=u.iconAction("send","发送",this::send);row.addView(send,new LinearLayout.LayoutParams(u.dp(48),u.dp(48)));view.addView(row);status=u.text("",12,u.muted,false);u.add(view,status,2);extras=u.row();retry=u.button("重试识别",false,()->begin(true));cancel=u.button("取消语音",false,()->{session.cancel();voice.discard();status.setText("");update();});extras.addView(retry);extras.addView(cancel);u.add(view,extras,2);input.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence t,int x,int y,int z){}public void onTextChanged(CharSequence t,int x,int y,int z){draft.accept(t.toString());update();}public void afterTextChanged(Editable e){}});update();}
 private void mic(){if(session.phase()==SpeechSession.Phase.RECORDING){session.transcribing(currentOwner);voice.stop();status.setText("正在转成文字…");update();}else if(!voice.active())begin(false);}
 private long currentOwner;
 private void begin(boolean again){beforeVoice=input.getText().toString().trim();currentOwner=session.begin();final long owner=currentOwner;VoiceInput.Listener listener=new VoiceInput.Listener(){public void state(String text){if(session.accepts(owner)){status.setText(text);update();}}public void phase(SpeechSession.Phase phase){if(phase==SpeechSession.Phase.PERMISSION)session.awaitPermission(owner);else if(phase==SpeechSession.Phase.RECORDING)session.recording(owner);else if(phase==SpeechSession.Phase.TRANSCRIBING)session.transcribing(owner);update();}public void transcript(String text){SpeechSession.Result result=session.complete(owner,text);if(result==SpeechSession.Result.IGNORED)return;if(result==SpeechSession.Result.ERROR){status.setText("没有得到文字，可重试录音或打字。");update();return;}String complete=beforeVoice.isEmpty()?text:beforeVoice+"\n"+text;input.setText(complete);input.setSelection(input.length());status.setText("已转成文字，可以编辑或发送。");update();if(result==SpeechSession.Result.SUBMIT)route.accept(complete);}public void failed(String text){if(session.accepts(owner)){session.fail(owner);status.setText(text+(voice.hasDraft()?" · 录音已保留":""));update();}}public void finished(){update();}};if(again)voice.retry(listener);else voice.start(listener);update();}
 private void send(){switch(session.send(!input.getText().toString().trim().isEmpty())){case STOP_AND_WAIT:voice.stop();status.setText("正在转成文字，完成后会发送。");update();break;case WAIT:status.setText("正在处理语音，完成后会发送。");update();break;case TEXT:route.accept(input.getText().toString().trim());break;default:status.setText(voice.hasDraft()?"上一段录音未识别完成，可点重试识别或输入文字。":"先说一句，或输入文字。");update();}}
 private void update(){SpeechSession.Phase p=session.phase();boolean processing=p==SpeechSession.Phase.TRANSCRIBING||p==SpeechSession.Phase.PERMISSION;view.setKeepScreenOn(p==SpeechSession.Phase.RECORDING||processing);input.setEnabled(p!=SpeechSession.Phase.RECORDING&&!processing);mic.setContentDescription(p==SpeechSession.Phase.RECORDING?"结束录音":processing?"正在处理":"说话");mic.setEnabled(!processing);send.setContentDescription(p==SpeechSession.Phase.RECORDING?"结束并发送":processing?"识别后发送":"发送");cancel.setVisibility(voice.active()||voice.hasDraft()?View.VISIBLE:View.GONE);retry.setVisibility(!voice.active()&&voice.hasDraft()?View.VISIBLE:View.GONE);extras.setVisibility(voice.active()||voice.hasDraft()?View.VISIBLE:View.GONE);status.setVisibility(status.length()>0?View.VISIBLE:View.GONE);send.setEnabled(p==SpeechSession.Phase.RECORDING||processing||input.getText().toString().trim().length()>0);}
 void cancel(){session.cancel();voice.cancel();update();}
}
