package cn.xigua.childcare;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.io.*;
import java.util.*;

public final class MainActivity extends Activity {
    private CareApp app;private Ui u;private VoiceInput voice;private CareComposer composer;private LinearLayout root,body,playerBar,careComposer;private ScrollView scroll;private LinearLayout bottomBar;private final Deque<String> backRoutes=new ArrayDeque<>();private final Map<String,Integer> scrollPositions=new HashMap<>();
    private String page="today",mode="qa",category="white_noise";private LocalDate date=LocalDate.now(ZoneId.of("Asia/Shanghai"));private ZoneId zone=ZoneId.of("Asia/Shanghai");
    private final Map<String,String> drafts=new HashMap<>();private JSONObject summary,active,latest;private List<JSONObject> timeline=new ArrayList<>(),reminders=new ArrayList<>(),tracks=new ArrayList<>(),conflicts=new ArrayList<>();
    private int historyPage,audioPage;private boolean catalogHasMore;private EditText handoffInput;private JSONObject restoreForm,formPrevious;private String formKind;private EditText formFrom,formUntil,formAmount,formNote;private Spinner formDetail,formCaregiver;
    private String child="西瓜",syncStatus="本地记录 · 尚未连接云端",handoff="";private int pending,refreshId;private boolean visible;private TextView voiceStatus;private EditText prompt;private Dialog sheet;
    private List<JSONObject> sessions=new ArrayList<>();private String routeStatus="可以记照护、问问题、听故事或播放声音。";
    private int aiPollAttempts;private boolean aiPollInFlight;
    private boolean pendingJob(){for(JSONObject r:sessions)if(Arrays.asList("queued","running","pending").contains(r.optString("status")))return true;return false;}
    private boolean shouldPoll(){return visible&&Arrays.asList("today","conversation").contains(page)&&pendingJob()&&aiPollAttempts<40;}
    private final Runnable pollJobs=()->pollJobs();
    private void pollJobs(){if(!shouldPoll()||aiPollInFlight)return;aiPollInFlight=true;aiPollAttempts++;app.network.execute(()->{try{AiEngine.process(app);}finally{app.main.post(()->{aiPollInFlight=false;if(shouldPoll()){app.main.removeCallbacks(pollJobs);app.main.postDelayed(pollJobs,1500);}});}});}
    private final Runnable observer=()->refresh();
    private final Runnable tick=new Runnable(){public void run(){if(visible){refresh();app.main.postDelayed(this,60000);}}};
    @Override public void onCreate(Bundle b){super.onCreate(b);app=(CareApp)getApplication();voice=new VoiceInput(this);if(b!=null){page=b.getString("page","today");mode=b.getString("mode","qa");category=b.getString("category","white_noise");date=LocalDate.parse(b.getString("date",date.toString()));historyPage=b.getInt("historyPage",0);audioPage=b.getInt("audioPage",0);if(b.containsKey("form"))restoreForm=Store.json(b.getString("form"));}else if(getIntent().hasExtra("page"))page=getIntent().getStringExtra("page");
        if(Arrays.asList("qa","story","companion").contains(page))page="today";
        drafts.put("care","");
        drafts.put("handoff",getPreferences(0).getString("handoffDraft",app.store.get("handoff","")));drafts.put("qa","");drafts.put("story","");
        getPreferences(0).edit().remove("care").remove("qa").remove("story").apply();
        getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
    }
    @Override public void onRequestPermissionsResult(int code,String[] permissions,int[] results){super.onRequestPermissionsResult(code,permissions,results);if(code==41)voice.permissionResult(results);}
    @Override protected void onResume(){super.onResume();visible=true;aiPollAttempts=0;Updates.maybeCheck(app);app.observe(observer);refresh();app.main.postDelayed(tick,60000);}
    @Override protected void onPause(){visible=false;app.remove(observer);app.main.removeCallbacks(tick);app.main.removeCallbacks(pollJobs);if(!voice.awaitingPermission()){if(composer!=null)composer.cancel();else voice.cancel();}getPreferences(0).edit().remove("care").remove("qa").remove("story").putString("handoffDraft",drafts.getOrDefault("handoff","")).apply();if(voiceStatus!=null)voiceStatus.setText("已离开前台，录音已取消");super.onPause();}
    @Override protected void onDestroy(){refreshId++;voice.cancel();if(sheet!=null)sheet.dismiss();super.onDestroy();}
    @Override protected void onSaveInstanceState(Bundle b){b.putString("page",page);b.putString("mode",mode);b.putString("category",category);b.putString("date",date.toString());b.putInt("historyPage",historyPage);b.putInt("audioPage",audioPage);if(formFrom!=null&&sheet!=null&&sheet.isShowing())b.putString("form",Store.obj("kind",formKind,"previous",formPrevious,"from",formFrom.getText().toString(),"until",formUntil.getText().toString(),"amount",formAmount.getText().toString(),"note",formNote.getText().toString(),"detail",formDetail.getSelectedItemPosition(),"caregiver",formCaregiver.getSelectedItemPosition()).toString());super.onSaveInstanceState(b);}
    @Override public void onBackPressed(){if(prompt!=null&&prompt.hasFocus()){prompt.clearFocus();((android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(prompt.getWindowToken(),0);return;}if(!backRoutes.isEmpty()){go(backRoutes.pop());}else if(!"today".equals(page))go("today");else super.onBackPressed();}
    private boolean rootRoute(String target){return Arrays.asList("today","records","my","audio").contains(target);}
    private void nav(String target){if(target.equals(page))return;if(rootRoute(target))backRoutes.clear();else backRoutes.push(page);go(target);}
    private void go(String target){if(scroll!=null)scrollPositions.put(page,scroll.getScrollY());if(composer!=null)composer.cancel();else voice.cancel();app.main.removeCallbacks(pollJobs);aiPollAttempts=0;prompt=null;handoffInput=null;composer=null;page=target;if("today".equals(target))date=LocalDate.now(zone);refresh();}
    private void refresh(){if(!visible)return;final int owner=++refreshId;final String target=page,requestMode=mode,cat=category;final LocalDate selected=date;
        app.database.execute(()->{try{
            Store s=app.store;ZoneId z=ZoneId.of(s.get("timezone","Asia/Shanghai"));long[] d=CareRules.day(selected,z);JSONObject sum=s.summary(d[0],d[1],System.currentTimeMillis()),sleep=s.activeSleep(),req=s.latestRequest(requestMode);List<JSONObject> rows=s.timeline(d[0],d[1],historyPage);
            List<JSONObject> rs=s.query("SELECT * FROM reminders WHERE done=0 ORDER BY due LIMIT 100"),ts=s.query("SELECT * FROM tracks WHERE category=? ORDER BY local DESC,title,id LIMIT 100 OFFSET ?",cat,String.valueOf(audioPage*100L)),cs=s.query("SELECT * FROM outbox WHERE status='conflict' ORDER BY seq LIMIT 100");
            List<JSONObject> conversations=s.query("SELECT * FROM requests ORDER BY created DESC,id DESC LIMIT 5");
            String name=s.get("child_name","西瓜"),status=s.get("sync_status","本地记录 · 尚未连接云端"),note=s.get("handoff","");int count=s.pending();boolean more=!s.get("catalog_next_"+cat,"").isEmpty();
            app.main.post(()->{if(!visible||owner!=refreshId||!target.equals(page))return;sessions=conversations;zone=z;summary=sum;active=sleep;latest=req;timeline=rows;reminders=rs;tracks=ts;conflicts=cs;child=name;syncStatus=status;handoff=note;pending=count;catalogHasMore=more;render();});
        }catch(Exception e){app.main.post(()->toast("读取记录失败，请重试；原数据已保留"));}});
    }
    private void render(){if((prompt!=null&&(prompt.hasFocus()||voice.active())&&Arrays.asList("today","conversation").contains(page))||(handoffInput!=null&&handoffInput.hasFocus()&&"handoff".equals(page))){if(playerBar!=null){playerBar.removeAllViews();player();}return;}int old=scrollPositions.getOrDefault(page,0);if(scroll!=null&&page.equals(scroll.getTag()))old=scroll.getScrollY();final int position=old;u=new Ui(this,false);setTheme(R.style.AppTheme);root=u.column();careComposer=null;root.setBackgroundColor(u.bg);
        getWindow().setNavigationBarColor(u.bg);getWindow().setStatusBarColor(u.bg);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
        root.setOnApplyWindowInsetsListener((v,insets)->{root.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets.consumeSystemWindowInsets();});
        toolbar();scroll=new ScrollView(this);scroll.setTag(page);scroll.setFillViewport(true);body=u.column();body.setPadding(u.dp(16),u.dp(4),u.dp(16),u.dp(16));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        switch(page){case "records":records();break;case "sleep":sleep();break;case "audio":audio();break;case "my":my();break;case "settings":settings();break;case "backup":backup();break;case "conversation":conversation();break;case "updates":updates();break;case "services":new AiSettings(this,app,u).render(body);break;case "reminders":reminderPage();break;case "handoff":handoffPage();break;case "cloud":cloud();break;default:today();}
        if(careComposer!=null)root.addView(careComposer);playerBar=u.column();root.addView(playerBar);player();bottom();setContentView(root);root.requestApplyInsets();scroll.post(()->scroll.scrollTo(0,position));root.getViewTreeObserver().addOnGlobalLayoutListener(()->{android.graphics.Rect r=new android.graphics.Rect();root.getWindowVisibleDisplayFrame(r);boolean keyboard=root.getRootView().getHeight()-r.bottom>u.dp(180);if(bottomBar!=null)bottomBar.setVisibility(keyboard?View.GONE:View.VISIBLE);});if(restoreForm!=null){JSONObject draft=restoreForm;restoreForm=null;app.main.post(()->{edit(draft.optJSONObject("previous"),draft.optString("kind"));if(formFrom!=null){formFrom.setText(draft.optString("from"));formUntil.setText(draft.optString("until"));formAmount.setText(draft.optString("amount"));formNote.setText(draft.optString("note"));formDetail.setSelection(draft.optInt("detail"));formCaregiver.setSelection(draft.optInt("caregiver"));}});}
    }
    private void toolbar(){LinearLayout bar=u.row();bar.setPadding(u.dp(8),0,u.dp(8),0);bar.setMinimumHeight(u.dp(56));boolean home="today".equals(page);if(!rootRoute(page))bar.addView(u.iconAction("back","返回",this::onBackPressed),new LinearLayout.LayoutParams(u.dp(48),u.dp(48)));LinearLayout label=u.column();String title=home?child:"records".equals(page)?"照护记录":"my".equals(page)?"家庭":"settings".equals(page)?"设置":"services".equals(page)?"AI 服务与模型":"cloud".equals(page)?"家庭同步":"backup".equals(page)?"备份与导出":"audio".equals(page)?"音频库":"reminders".equals(page)?"照护提醒":"conversation".equals(page)?"对话":"updates".equals(page)?"版本与更新":"handoff".equals(page)?"照护交接":"睡眠";label.addView(u.text(title,20,u.ink,true));if(home)label.addView(u.text(LocalDate.now(zone).format(DateTimeFormatter.ofPattern("M月d日 E",Locale.CHINA)),12,u.muted,false));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.leftMargin=u.dp(8);bar.addView(label,lp);if(rootRoute(page))bar.addView(u.iconAction("settings","设置",()->nav("settings")),new LinearLayout.LayoutParams(u.dp(48),u.dp(48)));if("records".equals(page))bar.addView(u.iconAction("qa","照护交接",()->nav("handoff")),new LinearLayout.LayoutParams(u.dp(48),u.dp(48)));root.addView(bar);}
    private void header(String eyebrow,String title){}
    private void status(){TextView t=u.text(pending>0?pending+" 项待同步 · "+syncStatus:syncStatus,12,u.muted,false);u.add(body,t,8);}
    private void bottom(){LinearLayout bar=u.row();bottomBar=bar;bar.setPadding(u.dp(8),0,u.dp(8),0);bar.setBackgroundColor(u.surface);String[] titles={"照护","记录","音频","家庭"},pages={"today","records","audio","my"},icons={"qa","records","audio_library","my"};String current=rootRoute(page)?page:"reminders".equals(page)||"conversation".equals(page)?"today":"handoff".equals(page)||"sleep".equals(page)?"records":"";
        for(int k=0;k<4;k++){final String p=pages[k];boolean selected=current.equals(p);LinearLayout tab=u.column();tab.setGravity(Gravity.CENTER);tab.setMinimumHeight(u.dp(56));if(selected)tab.setBackground(u.shape(u.soft,12));tab.addView(u.assetIcon(icons[k],22));TextView caption=u.text(titles[k],12,selected?u.green:u.muted,selected);caption.setGravity(Gravity.CENTER);u.add(tab,caption,2);tab.setSelected(selected);tab.setContentDescription(titles[k]+(selected?"，已选中":""));tab.setClickable(true);tab.setFocusable(true);tab.setOnClickListener(v->nav(p));bar.addView(tab,new LinearLayout.LayoutParams(0,-2,1));}root.addView(bar);}
    private void makeComposer(){composer=new CareComposer(this,u,voice,"",large(),text->drafts.put("care",text),this::routeCare);careComposer=composer.view;prompt=composer.input;}
    private String sectionIcon(String title){if(title.contains("提醒"))return "timer";if(title.contains("照护"))return "records";if(title.contains("回复")||title.contains("对话"))return "story";if(title.contains("同步"))return "sync";return "settings";}
    private void sectionAction(String title,String action,Runnable click){LinearLayout row=u.row();row.setMinimumHeight(u.dp(40));row.addView(u.assetIcon(sectionIcon(title),24),new LinearLayout.LayoutParams(u.dp(32),u.dp(32)));row.addView(u.text(title,18,u.ink,true),new LinearLayout.LayoutParams(0,-2,1));TextView button=u.button(action,false,click);button.setBackgroundColor(Color.TRANSPARENT);button.setMinHeight(u.dp(40));button.setPadding(u.dp(12),u.dp(4),u.dp(4),u.dp(4));row.addView(button);u.add(body,row,8);}
    private void today(){makeComposer();
        if(active!=null){LinearLayout row=u.row();row.setMinimumHeight(u.dp(72));row.setPadding(u.dp(12),u.dp(8),u.dp(8),u.dp(8));row.setBackground(u.shape(u.green,16));LinearLayout labels=u.column();labels.addView(u.text("正在睡 · "+duration(System.currentTimeMillis()-active.optLong("start")),18,Color.WHITE,true));u.add(labels,u.text(time(active.optLong("start"))+" 开始",12,Color.WHITE,false),4);row.addView(labels,new LinearLayout.LayoutParams(0,-2,1));row.addView(u.button("醒了",false,()->confirmSleep(false)));u.add(body,row,4);}
        compactMetrics();LinearLayout quick=u.row();quick(quick,"feeding","喂奶",()->edit(null,"feeding"));quick(quick,"sleep","睡觉",()->confirmSleep(active==null));quick(quick,"diaper","尿布",()->edit(null,"diaper"));quick(quick,"plus","更多",this::chooseRecord);u.add(body,quick,8);
        sectionAction("照护提醒","全部",()->nav("reminders"));if(reminders.isEmpty())u.item(body,"没有待办提醒","","添加",this::addReminder);else{JSONObject r=reminders.get(0);u.item(body,r.optString("title"),datetime(r.optLong("due"))+(r.optLong("due")<System.currentTimeMillis()?" · 已到时间":""),"完成",()->work(()->Reminders.done(this,r.optString("id")),"提醒已完成"));}
        if(pending>0||!conflicts.isEmpty())u.item(body,"家庭同步",pending+" 项待同步","查看",()->nav("cloud"));
        if(!sessions.isEmpty()){JSONObject r=sessions.get(0);sectionAction("最近回复","打开对话",()->nav("conversation"));LinearLayout reply=u.card(body,u.surface);TextView prompt=u.text(r.optString("prompt"),13,u.muted,false);prompt.setMaxLines(1);prompt.setEllipsize(TextUtils.TruncateAt.END);reply.addView(prompt);TextView answer=u.text(r.optString("response").isEmpty()?requestStatus(r.optString("status")):r.optString("response"),15,u.ink,false);answer.setMaxLines(3);answer.setEllipsize(TextUtils.TruncateAt.END);u.add(reply,answer,4);reply.setClickable(true);reply.setFocusable(true);reply.setContentDescription("打开完整对话");reply.setOnClickListener(v->nav("conversation"));}
        sectionAction("最近照护","全部记录",()->nav("records"));if(timeline.isEmpty())u.add(body,u.label("还没有记录，点上方快捷登记即可开始。"),4);else for(int i=Math.max(0,timeline.size()-3);i<timeline.size();i++){JSONObject e=timeline.get(i);u.item(body,CareTimeline.actor(e.optString("caregiver_name"))+" · "+CareTimeline.action(e.optString("kind"),e.optDouble("amount"),e.optString("detail"),e.optLong("duration"),e.optInt("active")==1),time(e.optLong("start")),null,()->details(e));}schedulePoll();
    }
    private void schedulePoll(){if(shouldPoll()&&!aiPollInFlight){app.main.removeCallbacks(pollJobs);app.main.postDelayed(pollJobs,1500);}if(pendingJob()&&aiPollAttempts>=40)u.add(body,u.button("继续查询回复",false,()->{aiPollAttempts=0;app.network.execute(()->AiEngine.process(app));}),8);}
    private void conversation(){makeComposer();if(sessions.isEmpty())u.add(body,u.label("说说宝宝的情况，或请我讲一个故事。"),8);for(JSONObject r:sessions)response(r);schedulePoll();}
    private void compactMetrics(){LinearLayout row=u.row();row.setBackground(u.shape(u.surface,16));row.setMinimumHeight(u.dp(64));String[] names={"喂奶 · "+summary.optLong("feeds")+" 次","已睡","换尿布"},values={summary.isNull("milk")?(summary.optLong("feeds")==0?"—":"未知"):CareRules.quantity(summary.optDouble("milk"))+" ml",duration(summary.optLong("sleep_ms")),summary.optLong("diaper")+" 次"};for(int i=0;i<3;i++){LinearLayout col=u.column();col.setPadding(u.dp(10),u.dp(8),u.dp(4),u.dp(8));col.addView(u.text(values[i],large()?18:21,u.ink,true));col.addView(u.text(names[i],12,u.muted,false));row.addView(col,new LinearLayout.LayoutParams(0,-2,1));}u.add(body,row,8);}
    private void playTrack(JSONObject t){voice.cancel();PlaybackService.play(this,t.optString("title"),t.optString("url"),"white_noise".equals(t.optString("category")));}
    private void playRain(){app.database.execute(()->{try{File f=DiskMedia.ambience(this);app.main.post(()->PlaybackService.play(this,"轻雨 · 离线环境音",f.getAbsolutePath(),true));}catch(Exception e){app.main.post(()->toast("雨声暂时不可用，请重试"));}});}
    private void routeCare(String content){if(prompt==null)return;String text=content.trim();if(text.isEmpty()){toast("先说一句或输入文字");return;}voice.cancel();prompt.clearFocus();((android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(prompt.getWindowToken(),0);IntentRouter intent=IntentRouter.classify(text);
        drafts.put("care","");prompt.setText("");
        switch(intent.action){
            case "clarify":routeStatus="请一次说一个动作；记录会先确认，不会自动保存。";refresh();break;
            case "records":nav("records");break;case "handoff":nav("handoff");break;case "family":nav("my");break;case "updates":nav("updates");break;case "reminder":addReminder();break;
            case "audio":category=intent.category;if(text.contains("雨声")){app.database.execute(()->{try{File f=DiskMedia.ambience(this);app.main.post(()->PlaybackService.play(this,"轻雨 · 离线环境音",f.getAbsolutePath(),true));}catch(Exception e){app.main.post(()->toast("雨声暂时不可用，请重试"));}});}else nav("audio");break;
            case "stop":PlaybackService.control(this,"stop");break;case "pause":PlaybackService.control(this,"pause");break;case "resume":PlaybackService.control(this,"resume");break;
            case "sleep_start":confirmSleep(true);break;case "sleep_end":confirmSleep(false);break;
            case "record":String detail="feeding".equals(intent.kind)?text.contains("母乳")?"母乳":text.contains("奶粉")?"奶粉":"其他":"diaper".equals(intent.kind)?text.contains("便")?text.contains("尿")?"尿便都有":"大便":text.contains("尿")||text.contains("湿")?"尿湿":"":"";JSONObject candidate=Store.obj("id","","kind",intent.kind,"start",System.currentTimeMillis(),"end",0,"amount",decimalAmount(text),"detail",detail,"note",text,"require_end",IntentRouter.historical(text)&&"sleep".equals(intent.kind));edit(candidate,intent.kind);if(IntentRouter.historical(text)){formFrom.setText("");toast("请确认这次补记的实际发生时间");}break;
            default:mode="story".equals(intent.action)?"story":"qa";sendAi(mode);
        }
    }
    private static double decimalAmount(String text){return CareRules.voiceQuantity(text);}
    private void confirmSleep(boolean start){if(start==(active!=null)){toast(start?"已经在记录睡眠，可先结束当前睡眠":"当前没有进行中的睡眠");return;}new AlertDialog.Builder(this).setTitle(start?"开始记录睡眠？":"宝宝已醒，结束睡眠？").setMessage("照护对象："+child+"；时间："+datetime(System.currentTimeMillis())).setNegativeButton("取消",null).setPositiveButton("确认",(d,w)->sleepToggle()).show();}
    private void response(JSONObject r){LinearLayout card=u.card(body,u.surface);String m=r.optString("mode");u.add(card,u.text(("story".equals(m)?"故事 · ":"问答 · ")+requestStatus(r.optString("status")),18,u.ink,true),0);u.add(card,u.label(r.optString("prompt")),10);String reply=r.optString("response");if(!reply.isEmpty()){TextView t=u.text(reply,17,u.ink,false);t.setTextIsSelectable(true);u.add(card,t,14);u.add(card,u.button("朗读",false,()->{voice.cancel();PlaybackService.speak(this,"story".equals(m)?"西瓜故事":"西瓜问答",reply);}),12);}if(!r.optString("error").isEmpty())u.add(card,u.label(r.optString("error")),8);if(Arrays.asList("queued","running","pending").contains(r.optString("status")))u.add(card,u.button("取消请求",false,()->cancelAi(r.optString("id"))),12);else if(!"completed".equals(r.optString("status")))u.add(card,u.button("重试",false,()->{prompt.setText(r.optString("prompt"));sendAi(m);}),12);}
    private void quick(LinearLayout parent,String icon,String title,Runnable click){LinearLayout item=u.row();item.setGravity(Gravity.CENTER);item.setMinimumHeight(u.dp(48));item.setBackground(u.shape(u.soft,12));item.addView(u.icon(icon,u.green,18));TextView caption=u.text(title,14,u.green,true);LinearLayout.LayoutParams text=new LinearLayout.LayoutParams(-2,-2);text.leftMargin=u.dp(4);item.addView(caption,text);item.setClickable(true);item.setFocusable(true);item.setContentDescription("记录"+title);item.setOnClickListener(v->click.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(u.dp(2),0,u.dp(2),0);parent.addView(item,p);}
    private void metrics(){LinearLayout row=large()?u.column():u.row();String[] names={"喂养量","睡眠","尿布"},values={(summary.isNull("milk")?(summary.optLong("feeds")==0?"—":"未知"):CareRules.quantity(summary.optDouble("milk"))+" ml"),duration(summary.optLong("sleep_ms")),summary.optLong("diaper")+" 次"};for(int k=0;k<3;k++){LinearLayout col=u.column();col.setPadding(u.dp(8),u.dp(12),u.dp(6),u.dp(12));col.addView(u.text(values[k],20,u.ink,true));u.add(col,u.label(names[k]),8);row.addView(col,large()?new LinearLayout.LayoutParams(-1,-2):new LinearLayout.LayoutParams(0,-2,1));}u.add(body,row,8);if(summary.optLong("unknown_milk")>0)u.add(body,u.label(summary.optLong("unknown_milk")+" 次喂养数量未知，未计入合计。"),4);if(summary.optLong("active_sleep_ms")>0)u.add(body,u.label("睡眠进行中 "+duration(summary.optLong("active_sleep_ms"))+"，未计入已完成睡眠。"),4);}
    private void records(){header("每个小变化，都值得留下","记录与历史");LinearLayout dateRow=large()?u.column():u.row();addWeighted(dateRow,u.button("前一天",false,()->{date=date.minusDays(1);historyPage=0;refresh();}));addWeighted(dateRow,u.button(date.format(DateTimeFormatter.ofPattern("M月d日")),false,this::pickDate));addWeighted(dateRow,u.button("后一天",false,()->{date=date.plusDays(1);historyPage=0;refresh();}));u.add(body,dateRow,18);status();metrics();
        LinearLayout quick=large()?u.column():u.row();addWeighted(quick,u.button("记喂奶",true,()->edit(null,"feeding")));addWeighted(quick,u.button("记换尿布",false,()->edit(null,"diaper")));u.add(body,quick,14);u.add(body,u.button("新增 / 补记",false,()->chooseRecord()),10);u.section(body,"这一天的时间线","按发生时间从早到晚 · 谁、几点、做了什么");timeline(100);LinearLayout pages=u.row();if(historyPage>0)addWeighted(pages,u.button("上一页",false,()->{historyPage--;if(scroll!=null)scroll.scrollTo(0,0);refresh();}));if(timeline.size()==100)addWeighted(pages,u.button("下一页",false,()->{historyPage++;if(scroll!=null)scroll.scrollTo(0,0);refresh();}));u.add(body,pages,14);u.add(body,u.label("第 "+(historyPage+1)+" 页"),8);
    }
    private void timeline(int max){
        if(timeline.isEmpty()){LinearLayout empty=u.card(body,u.surface);u.add(empty,u.text("这一天还没有记录",18,u.ink,true),0);u.add(empty,u.label("记一次喂奶或换尿布，就会留下谁、何时、做了什么。"),8);return;}
        boolean undated=false;int count=Math.min(max,timeline.size());
        for(int i=0;i<count;i++){
            JSONObject e=timeline.get(i);boolean unknown=e.optLong("start")==0;
            if(unknown&&!undated){u.section(body,"发生时间未登记","以下记录不计入这一天的合计。");undated=true;}
            String clock=CareTimeline.clock(e.optLong("start"),zone,date),actor=CareTimeline.actor(e.optString("caregiver_name"));
            String action=CareTimeline.action(e.optString("kind"),e.optDouble("amount"),e.optString("detail"),e.optLong("duration"),e.optInt("active")==1);
            LinearLayout row=u.row();row.setGravity(Gravity.TOP);TextView timeLabel=u.text(clock,large()?14:15,u.muted,true);timeLabel.setGravity(Gravity.END);timeLabel.setPadding(0,u.dp(18),u.dp(6),0);row.addView(timeLabel,new LinearLayout.LayoutParams(u.dp(large()?90:68),-2));
            View rail=new TimelineRail(this,u,i==0||unknown&&timeline.get(Math.max(0,i-1)).optLong("start")!=0,i==count-1||i+1<count&&timeline.get(i+1).optLong("start")==0&&!unknown);row.addView(rail,new LinearLayout.LayoutParams(u.dp(18),-1));
            LinearLayout card=u.column();card.setPadding(u.dp(12),u.dp(12),u.dp(12),u.dp(12));card.setBackground(u.shape(u.surface,16));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,-2,1);cp.bottomMargin=u.dp(8);cp.leftMargin=u.dp(6);row.addView(card,cp);
            u.add(card,u.text(actor,18,u.ink,true),0);u.add(card,u.text(action,16,u.ink,false),6);
            if("feeding".equals(e.optString("kind"))&&!e.optString("detail").isEmpty())u.add(card,u.label(e.optString("detail")),6);
            if(e.optInt("pending")>0)u.add(card,u.label("待同步"),6);if(!e.optString("note").isEmpty())u.add(card,u.label(e.optString("note")),6);
            card.setClickable(true);card.setFocusable(true);card.setContentDescription(actor+"，"+clock.replace('\n',' ')+"，"+action+"，点按查看详情");card.setOnClickListener(v->details(e));u.add(body,row,0);
        }
    }
    private void sleep(){header("轻一点，陪宝宝好好睡","睡眠");LinearLayout card=u.card(body,u.soft);u.add(card,u.text(active==null?"现在没有进行中的睡眠":"正在睡 · "+duration(System.currentTimeMillis()-active.optLong("start")),24,u.ink,true),0);u.add(card,u.label(active==null?"开始后不需要一直打开应用。":"开始 "+datetime(active.optLong("start"))+"\n计时保存在手机，重启后可以继续。"),12);u.add(card,u.button(active==null?"开始睡眠":"醒来了 · 结束睡眠",true,this::sleepToggle),18);u.add(body,u.button("补记一段睡眠",false,()->edit(null,"sleep")),18);u.add(body,u.button("查看睡眠历史",false,()->nav("records")),12);}
    private void sleepToggle(){work(()->app.store.toggleSleep(System.currentTimeMillis()),"睡眠状态已保存");}
    private void sendAi(String m){aiPollAttempts=0;String text=prompt.getText().toString().trim();prompt.setText("");drafts.put("care","");prompt.clearFocus();((android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(prompt.getWindowToken(),0);if(text.isEmpty()){toast("先写一点或用语音输入");return;}voice.cancel();if(pendingJob()){toast("当前请求尚未结束，可先取消");return;}final JSONObject provider;try{provider=Providers.snapshot(new Providers(this,app.store).resolve("chat"));}catch(Exception e){toast(e.getMessage());return;}String id=UUID.randomUUID().toString();app.database.execute(()->{app.store.set("request_provider_"+id,provider.toString());app.store.request(id,m,text);app.changed();app.network.execute(()->AiEngine.process(app));});}
    private void cancelAi(String id){app.database.execute(()->{JSONObject r=app.store.requestById(id);app.store.cancelRequest(id);AiEngine.cancel(id);app.changed();if(r!=null&&!r.optString("job").isEmpty())app.network.execute(()->new Api(app).cancelJob(r.optString("job")));});}
    private void audio(){header("声音，轻轻陪在身边","音频库");android.content.SharedPreferences last=getSharedPreferences("player",0);if(Arrays.asList("idle","stopped","complete").contains(PlaybackService.state)&&(!last.getString("url","").isEmpty()||!last.getString("speech_text","").isEmpty())){LinearLayout recovery=u.card(body,u.soft);u.add(recovery,u.text("上次播放 · "+last.getString("title","音频"),17,u.ink,true),0);boolean speech="speech".equals(last.getString("mode",""));u.add(recovery,u.label(speech?"朗读已中断，可从头重读。":"打开应用后不会自动播音，可从保存的位置继续。"),8);u.add(recovery,u.button(speech?"从头朗读":"继续上次音频",false,()->PlaybackService.control(this,"resume")),12);}LinearLayout filters=large()?u.column():u.row();String[] names={"环境音","儿歌","故事","古典"},cats={"white_noise","song","story","classical"},assets={"lullaby","lullaby","story","classical"};for(int k=0;k<4;k++){final String cat=cats[k];LinearLayout item=u.column();item.setGravity(Gravity.CENTER);item.setPadding(u.dp(4),u.dp(4),u.dp(4),u.dp(4));item.addView(u.assetIcon(assets[k],28));TextView caption=u.text(names[k],13,category.equals(cat)?u.green:u.muted,category.equals(cat));caption.setGravity(Gravity.CENTER);u.add(item,caption,2);item.setBackground(u.shape(category.equals(cat)?u.soft:u.surface,12));item.setClickable(true);item.setFocusable(true);item.setContentDescription(names[k]);item.setOnClickListener(v->{category=cat;audioPage=0;refresh();});addWeighted(filters,item);}u.add(body,filters,18);u.add(body,u.label("儿歌、故事和古典音乐从家庭云端目录加载；环境音支持离线循环。"),12);
        LinearLayout timer=u.row();timer.addView(u.assetIcon("timer",30),new LinearLayout.LayoutParams(u.dp(40),u.dp(40)));TextView timerText=u.text("定时停止播放",15,u.ink,true);timer.addView(timerText,new LinearLayout.LayoutParams(0,-2,1));timer.setPadding(u.dp(10),u.dp(4),u.dp(10),u.dp(4));timer.setBackground(u.shape(u.surface,12));timer.setContentDescription("定时停止播放");timer.setClickable(true);timer.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("自动停止播放").setItems(new String[]{"15 分钟","30 分钟","60 分钟","取消定时"},(d,w)->{PlaybackService.timer(this,new int[]{15,30,60,0}[w]);toast("已更新播放定时");}).show());u.add(body,timer,12);
        if("white_noise".equals(category))u.add(body,u.button("播放离线轻雨声",true,()->app.database.execute(()->{try{File f=DiskMedia.ambience(this);app.main.post(()->PlaybackService.play(this,"轻雨 · 离线环境音",f.getAbsolutePath(),true));}catch(Exception e){app.main.post(()->toast("环境音生成失败，请重试"));}})),16);
        LinearLayout actions=u.row();addWeighted(actions,iconButton("import","导入手机音频",this::importAudio));addWeighted(actions,iconButton("refresh","刷新云端目录",()->{audioPage=0;final String selected=category;app.network.execute(()->new Api(app).catalog(selected));}));u.add(body,actions,12);
        if(tracks.isEmpty())u.add(body,u.label("这个分类还没有音频。可导入本地文件，或连接云端后刷新。"),24);
        for(JSONObject t:tracks){LinearLayout card=u.card(body,u.surface);u.add(card,u.text(t.optString("title"),19,u.ink,true),0);u.add(card,u.label(t.optInt("local")==1?"本地音频 · 离线可用":"云端音频 · 联网播放"),8);u.add(card,u.button("播放",false,()->{voice.cancel();PlaybackService.play(this,t.optString("title"),t.optString("url"),"white_noise".equals(t.optString("category")));}),14);if(t.optInt("local")==1)u.add(card,u.button("移除此音频",false,()->new AlertDialog.Builder(this).setMessage("移除本地音频文件？").setNegativeButton("保留",null).setPositiveButton("移除",(d,w)->work(()->{if(t.optString("url").equals(PlaybackService.source))PlaybackService.control(this,"stop");new File(t.optString("url")).delete();app.store.getWritableDatabase().delete("tracks","id=?",new String[]{t.optString("id")});},"已移除")).show()),8);}
        LinearLayout pagination=u.row();if(audioPage>0)addWeighted(pagination,u.button("上一页音频",false,()->{audioPage--;scroll.scrollTo(0,0);refresh();}));if(tracks.size()==100)addWeighted(pagination,u.button("下一页音频",false,()->{audioPage++;scroll.scrollTo(0,0);refresh();}));u.add(body,pagination,14);if(catalogHasMore){final String selected=category;u.add(body,u.button("加载更多云端音频",false,()->app.network.execute(()->new Api(app).catalogMore(selected))),12);}
    }
    private void player(){String s=PlaybackService.state;if("idle".equals(s)||"stopped".equals(s)||"complete".equals(s))return;playerBar.setPadding(u.dp(12),u.dp(4),u.dp(8),u.dp(4));playerBar.setBackgroundColor(u.soft);LinearLayout row=large()?u.column():u.row();TextView title=u.text(PlaybackService.title+" · "+("playing".equals(s)?"播放中":"paused".equals(s)?"已暂停":"buffering_paused".equals(s)?"准备中（已暂停）":"buffering".equals(s)?"正在准备":"播放失败"),14,u.ink,true);title.setMaxLines(2);title.setEllipsize(android.text.TextUtils.TruncateAt.END);row.addView(title,large()?new LinearLayout.LayoutParams(-1,-2):new LinearLayout.LayoutParams(0,-2,1));boolean pause="playing".equals(s)||"buffering".equals(s);TextView toggle=u.button("failed".equals(s)?"重试":pause?"暂停":"继续",false,()->PlaybackService.control(this,("playing".equals(PlaybackService.state)||"buffering".equals(PlaybackService.state))?"pause":"resume"));row.addView(toggle);row.addView(u.button("停止",false,()->PlaybackService.control(this,"stop")));playerBar.addView(row);if(!PlaybackService.error.isEmpty())u.add(playerBar,u.label(PlaybackService.error),4);}
    private void my(){new FamilyUi(this,app,u,this::refresh).render(body);}
    private void settings(){u.section(body,"服务与数据","");u.item(body,"AI 服务与模型","文字 · ASR · TTS · 视觉 · JEV",null,()->nav("services"));u.item(body,"家庭同步",pending>0?pending+" 项待同步":syncStatus,null,()->nav("cloud"));u.item(body,"备份与导出","家庭资料和照护记录的 ZIP 备份包",null,()->nav("backup"));u.section(body,"这部手机","");u.item(body,"提醒与通知","管理系统通知权限",null,()->startActivity(new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName())));u.item(body,"版本与更新",app.store.get("update_release","").isEmpty()?"检查家庭频道更新":"有新版本可更新",null,()->nav("updates"));}
    private void backup(){u.add(body,u.label("导出一个真正的 ZIP 备份包，包含家庭资料、全部记录、提醒、音频清单和校验文件。密钥与临时下载不进入备份。"),12);u.add(body,u.button("导出备份（ZIP）",true,this::export),16);u.add(body,u.label("备份包包含可读取的资料文件；此版本尚不提供整包恢复入口。"),12);}

    private void updates(){header("让每次升级都有依据","版本与更新");new UpdatesUi(this,app,u,this::refresh).render(body);}
    private void reminderPage(){header("帮你记住下一件小事","照护提醒");boolean granted=Build.VERSION.SDK_INT<33||checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED;u.add(body,u.label(granted?"通知已允许。系统省电可能推迟提醒，列表始终保留。":"通知尚未允许；提醒会保留在列表，但无法弹出通知。"),14);if(!granted)u.add(body,u.button("允许通知",false,()->requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},42)),12);u.add(body,u.button("添加提醒",true,this::addReminder),16);for(JSONObject r:reminders){LinearLayout card=u.card(body,u.surface);u.add(card,u.text(r.optString("title"),19,u.ink,true),0);u.add(card,u.label(datetime(r.optLong("due"))+(r.optLong("due")<System.currentTimeMillis()?" · 已到时间":"")),8);u.add(card,u.button("完成",false,()->work(()->Reminders.done(this,r.optString("id")),"提醒已完成")),12);}}
    private void handoffPage(){header("把照护，温柔地交到下一双手","照护交接");LinearLayout card=u.card(body,u.soft);String text=handoffText();u.add(card,u.text(text,17,u.ink,false),0);EditText note=u.input("给下一位照护者留个备注",drafts.getOrDefault("handoff",handoff),android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE);handoffInput=note;note.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence t,int a,int b,int c){}public void onTextChanged(CharSequence t,int a,int b,int c){drafts.put("handoff",t.toString());}public void afterTextChanged(Editable t){}});note.setFilters(new InputFilter[]{new InputFilter.LengthFilter(2000)});u.add(body,note,18);u.add(body,u.button("保存交接备注",true,()->work(()->app.store.set("handoff",note.getText().toString()),"备注已保存")),12);u.add(body,u.button("分享交接摘要",false,()->share(text+"\n备注："+note.getText())),12);u.add(body,u.label("交接备注当前保存在本机；分享会打开系统分享面板。"),12);}
    private String handoffText(){return child+" · "+date+"\n喂养 "+summary.optLong("feeds")+" 次 / "+(summary.isNull("milk")?"数量未知":CareRules.quantity(summary.optDouble("milk"))+" ml")+"\n已完成睡眠 "+duration(summary.optLong("sleep_ms"))+"；尿布 "+summary.optLong("diaper")+" 次\n"+(active==null?"没有进行中的睡眠":"睡眠进行中，开始于 "+datetime(active.optLong("start")))+"\n"+pending+" 项待同步 · 本地临时统计";}
    private String conflictText(String code){return "instance_context_missing".equals(code)?"这条记录创建时尚未连接备份服务，请确认后重新提交。":"instance_context_mismatch".equals(code)?"备份服务已改变，这条记录保留在本机，请先导出留存。":"generation_mismatch".equals(code)?"云端已清空旧记录，本机记录仍保留。":"云端记录有新修改，请选择保留的版本。";}
    private void cloud(){boolean paused="1".equals(app.store.get("sync_paused","0")),running="1".equals(app.store.get("sync_running","0"));status();u.add(body,u.label("家庭服务器已内置。联网时自动同步同一个宝宝的资料与照护记录。"),12);u.add(body,u.label("上次成功同步："+(app.store.get("sync_success","").isEmpty()?"尚未完成":app.store.get("sync_success",""))),8);LinearLayout actions=u.row();addWeighted(actions,iconButton("sync",running?"同步中…":"现在同步",this::startSync));addWeighted(actions,u.button(paused?"恢复自动同步":"暂停自动同步",false,this::toggleSync));u.add(body,actions,12);if(running)u.add(body,u.label("同步已开始，正在读取宝宝档案、照护记录和云端音频目录。页面会自动更新状态。"),8);if(paused)u.add(body,u.label("自动同步已暂停；本机记录仍会保存，恢复后会继续提交。"),8);if(!conflicts.isEmpty()){u.section(body,"需要确认的记录","原记录会保留，确认后再处理。");for(JSONObject op:conflicts){LinearLayout card=u.card(body,u.surface);u.add(card,u.text(conflictText(op.optString("error")),16,u.ink,true),0);u.add(card,u.button("采用云端版本",false,()->resolve(op,false)),8);u.add(card,u.button("保留本地并重新提交",false,()->resolve(op,true)),8);}}}
    private void startSync(){if("1".equals(app.store.get("sync_paused","0"))){toast("请先恢复自动同步");return;}if("1".equals(app.store.get("sync_running","0"))){toast("同步已经在进行中");return;}app.store.set("sync_running","1");app.store.set("sync_status","正在同步 · 已开始");app.changed();app.network.execute(()->{new Api(app).sync();app.store.set("sync_running","0");app.changed();});}
    private void toggleSync(){boolean paused="1".equals(app.store.get("sync_paused","0"));app.store.set("sync_paused",paused?"0":"1");if(paused)app.store.set("sync_status","同步已恢复，等待自动同步");else app.store.set("sync_status","同步已暂停");app.changed();if(paused)SyncService.schedule(this);}
    private void resolve(JSONObject op,boolean local){new AlertDialog.Builder(this).setMessage(local?"按当前云端修订重新提交本地内容？清空代次冲突需要另行显式恢复，本按钮不会恢复旧档案。":"采用云端版本并放弃该记录的本地待同步操作？").setNegativeButton("取消",null).setPositiveButton("确认",(d,w)->work(()->new Api(app).resolve(op,local),"冲突已处理")).show();}
    private void cloudStats(){app.network.execute(()->{try{JSONObject result=new Api(app).statistics(date,zone);app.main.post(()->new AlertDialog.Builder(this).setTitle("同口径云端统计").setMessage(serverSummary(result)).setPositiveButton("知道了",null).show());}catch(Exception e){app.main.post(()->toast("云端统计不可用，保留本地临时统计"));}});}
    private void chooseRecord(){new AlertDialog.Builder(this).setTitle("记录一件小事").setItems(new String[]{"喂养","睡眠补记","尿布","洗澡","趴玩","计时"},(d,w)->edit(null,new String[]{"feeding","sleep","diaper","bath","tummy","timer"}[w])).show();}
    private String serverSummary(JSONObject result){JSONObject care=result.optJSONObject("childcare");if(care==null)return "服务器未返回育儿统计。";return result.optString("start")+" · "+result.optString("timezone")+"\n已同步修订 "+result.optLong("at_revision")+"\n\n喂养 "+care.optLong("feeding_count")+" 次 / "+(care.isNull("milk_ml")?"数量未知":care.optString("milk_ml")+" ml")+"\n睡眠 "+duration((long)(care.optDouble("sleep_seconds",0)*1000))+"\n尿布 "+care.optLong("diaper_count")+" 次\n未知发生时间 "+result.optLong("unknown_time_count")+" 条\n\n本地仍有 "+pending+" 项待同步（含进行中的睡眠），两者暂不能视为相同总数。";}
    private void details(JSONObject e){new AlertDialog.Builder(this).setTitle(eventTitle(e)).setMessage(CareTimeline.actor(e.optString("caregiver_name"))+"\n"+datetime(e.optLong("start"))+"\n"+eventDetail(e)+"\n"+e.optString("note")+"\n修订 "+e.optLong("revision")+(e.optInt("pending")>0?" · 待同步":"")).setPositiveButton("编辑",(d,w)->edit(e,e.optString("kind"))).setNeutralButton("删除",(d,w)->new AlertDialog.Builder(this).setMessage("删除这条记录？可以撤销。联网后同步删除。").setNegativeButton("保留",null).setPositiveButton("删除",(x,y)->app.database.execute(()->{JSONObject before=app.store.delete(e.optString("id"));app.changed();app.main.post(()->new AlertDialog.Builder(this).setMessage("记录已删除").setPositiveButton("撤销删除",(a,b)->work(()->app.store.undo(before),"已撤销删除")).setNegativeButton("完成",null).show());})).show()).setNegativeButton("返回",null).show();}
    private void edit(JSONObject initial,String kind){final JSONObject previous;if(initial==null)previous=Store.obj("id","","kind",kind,"start",System.currentTimeMillis()-("sleep".equals(kind)?30*60000L:0),"end","sleep".equals(kind)?System.currentTimeMillis():0,"amount",150,"detail","","note","");else previous=initial;JSONObject registered=app.store.selectedMember();if(!previous.has("caregiver_id")){try{previous.put("caregiver_id",registered==null?"":registered.optString("id"));previous.put("caregiver_name",registered==null?"":FamilyRules.caregiverTitle(registered.optString("name"),registered.optString("relation")));}catch(JSONException e){throw new IllegalArgumentException(e);}}app.store.captureContext(previous);voice.cancel();LinearLayout fields=u.column();fields.setPadding(u.dp(20),u.dp(14),u.dp(20),u.dp(16));ScrollView wrap=new ScrollView(this);wrap.addView(fields);long start=previous==null?System.currentTimeMillis()-("sleep".equals(kind)?30*60000L:0):previous.optLong("start");long end=previous==null?System.currentTimeMillis():previous.optLong("end");if(!"sleep".equals(kind)&&previous==null)end=0;
        EditText from=u.input("发生时间：yyyy-MM-dd HH:mm",datetime(start),android.text.InputType.TYPE_CLASS_DATETIME);u.add(fields,u.label("照护对象："+child),0);
        final List<JSONObject> actors=new ArrayList<>();actors.add(Store.obj("id",previous.optString("caregiver_id"),"name",previous.optString("caregiver_name")));List<String> actorLabels=new ArrayList<>();actorLabels.add(CareTimeline.actor(previous.optString("caregiver_name"))+(!previous.optString("id").isEmpty()?"（原记录）":""));
        if(!previous.optString("caregiver_name").isEmpty()){actors.add(Store.obj("id","","name",""));actorLabels.add("照护者未登记");}
        for(JSONObject member:app.store.members()){String title=FamilyRules.caregiverTitle(member.optString("name"),member.optString("relation"));if(member.optInt("active")==1&&(!member.optString("id").equals(previous.optString("caregiver_id"))||!title.equals(previous.optString("caregiver_name")))){actors.add(Store.obj("id",member.optString("id"),"name",title));actorLabels.add(title);}}
        Spinner caregiver=new Spinner(this);caregiver.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,actorLabels));caregiver.setContentDescription("实际照护者");u.add(fields,u.label("实际照护者（可为补记选择其他人）"),10);u.add(fields,caregiver,6);u.add(fields,u.label("发生时间"),10);u.add(fields,from,8);EditText until=u.input("结束时间",end>0?datetime(end):"",android.text.InputType.TYPE_CLASS_DATETIME);if(Arrays.asList("sleep","tummy","timer").contains(kind)){u.add(fields,u.label(previous.optInt("active")==0&&!previous.optString("remote_json").isEmpty()?"结束时间（历史记录留空表示未登记）":"结束时间（睡眠留空代表进行中）"),12);u.add(fields,until,8);}
        EditText amount=u.input("数量",previous==null?"150":previous.optDouble("amount",0)==0?"":CareRules.quantity(previous.optDouble("amount")),android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL);Spinner detail=new Spinner(this);List<String> detailValues=new ArrayList<>(Arrays.asList("feeding".equals(kind)?new String[]{"奶粉","母乳","辅食","其他",""}:new String[]{"尿湿","大便","尿便都有",""}));if(!detailValues.contains(previous.optString("detail")))detailValues.add(0,previous.optString("detail"));final String[] choices=detailValues.toArray(new String[0]);String[] labels=choices.clone();for(int i=0;i<labels.length;i++)if(labels[i].isEmpty())labels[i]="未登记";ArrayAdapter<String> adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels);detail.setAdapter(adapter);if(previous!=null){for(int k=0;k<choices.length;k++)if(choices[k].equals(previous.optString("detail")))detail.setSelection(k);}
        if("feeding".equals(kind)){u.add(fields,u.label("数量（毫升；留空表示未知；辅食克数写备注）"),12);u.add(fields,amount,8);u.add(fields,detail,8);}else if("diaper".equals(kind))u.add(fields,detail,12);
        EditText note=u.input("可选备注",previous==null?"":previous.optString("note"),android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE);note.setFilters(new InputFilter[]{new InputFilter.LengthFilter(2000)});u.add(fields,note,14);
        formCaregiver=caregiver;formKind=kind;formPrevious=previous;formFrom=from;formUntil=until;formAmount=amount;formNote=note;formDetail=detail;AlertDialog d=new AlertDialog.Builder(this).setTitle(previous.optString("id").isEmpty()?"确认"+kindName(kind)+"记录":"编辑"+kindName(kind)).setView(wrap).setPositiveButton("保存",null).setNegativeButton("取消",null).create();sheet=d;d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{try{long t=previous!=null&&from.getText().toString().equals(datetime(previous.optLong("start")))?previous.optLong("start"):parse(from.getText().toString());long stop=Arrays.asList("sleep","tummy","timer").contains(kind)&&!until.getText().toString().trim().isEmpty()?(previous!=null&&until.getText().toString().equals(datetime(previous.optLong("end")))?previous.optLong("end"):parse(until.getText().toString())):0;double value="feeding".equals(kind)?(amount.getText().toString().trim().isEmpty()?0:Double.parseDouble(amount.getText().toString())):0;String detailText=Arrays.asList("feeding","diaper").contains(kind)?choices[detail.getSelectedItemPosition()]:"";JSONObject actor=actors.get(caregiver.getSelectedItemPosition());JSONObject e=Store.obj("_caregiver_changed",caregiver.getSelectedItemPosition()!=0,"_sync_context",previous.optJSONObject("_sync_context"),"caregiver_id",actor.optString("id"),"caregiver_name",actor.optString("name"),"id",previous==null?"":previous.optString("id"),"kind",kind,"start",t,"end",stop,"amount",value,"detail",detailText,"note",note.getText().toString(),"timezone",previous.optString("timezone",zone.getId()));if(previous!=null&&!previous.optString("id").isEmpty())e.put("_expected_revision",previous.optLong("revision"));if(previous.optBoolean("require_end")&&stop==0)throw new IllegalArgumentException("补记睡眠请填写实际结束时间");CareRules.validateAt(kind,value,t==0&&previous.optLong("start")==0&&!previous.optString("id").isEmpty()?1:t,stop,note.getText().toString(),System.currentTimeMillis());d.getButton(-1).setEnabled(false);app.database.execute(()->{try{app.store.save(e);app.changed();app.main.post(()->{d.dismiss();toast("记录已保存在手机");});SyncService.schedule(this);}catch(Exception ex){app.main.post(()->{d.getButton(-1).setEnabled(true);toast("保存失败："+(ex instanceof IllegalArgumentException?ex.getMessage():"可能已有进行中的睡眠"));});}});}catch(Exception ex){toast(ex instanceof IllegalArgumentException?ex.getMessage():"请填写有效时间与数量");}}));d.setOnDismissListener(x->{formFrom=null;formUntil=null;formAmount=null;formNote=null;formDetail=null;formCaregiver=null;sheet=null;refresh();});d.show();}
    private long parse(String text){LocalDateTime t;try{t=LocalDateTime.parse(text.trim(),DateTimeFormatter.ofPattern("uuuu-MM-dd HH:mm").withResolverStyle(java.time.format.ResolverStyle.STRICT));}catch(Exception e){throw new IllegalArgumentException("时间格式须为 yyyy-MM-dd HH:mm");}List<ZoneOffset> offsets=zone.getRules().getValidOffsets(t);if(offsets.size()!=1)throw new IllegalArgumentException("此时间处于夏令时跳跃/重复区间，请选择明确时间");return t.atOffset(offsets.get(0)).toInstant().toEpochMilli();}
    private void addReminder(){LinearLayout fields=u.column();fields.setPadding(u.dp(20),0,u.dp(20),0);EditText title=u.input("提醒什么", "",1),due=u.input("yyyy-MM-dd HH:mm",datetime(System.currentTimeMillis()+3600000),android.text.InputType.TYPE_CLASS_DATETIME);u.add(fields,title,10);u.add(fields,due,10);new AlertDialog.Builder(this).setTitle("添加照护提醒").setView(fields).setPositiveButton("保存",(d,w)->{try{long t=parse(due.getText().toString());work(()->{app.store.reminder(title.getText().toString(),t);Reminders.scheduleAll(this);},"提醒已保存");}catch(Exception e){toast(e.getMessage());}}).setNegativeButton("取消",null).show();}
    private void pickDate(){new DatePickerDialog(this,(view,y,m,d)->{date=LocalDate.of(y,m+1,d);historyPage=0;refresh();},date.getYear(),date.getMonthValue()-1,date.getDayOfMonth()).show();}
    private void importAudio(){startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("audio/*").addCategory(Intent.CATEGORY_OPENABLE),52);}
    private void export(){startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/zip").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"xigua-childcare-"+LocalDate.now(zone)+".zip"),51);}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();if(request==54)app.network.execute(()->Updates.importApk(app,uri));if(request==51)app.database.execute(()->{try(OutputStream out=getContentResolver().openOutputStream(uri)){BackupArchive.write(app,out);app.main.post(()->toast("ZIP 备份包已导出"));}catch(Exception e){app.main.post(()->toast("导出失败，请重新选择位置"));}});if(request==52){final String cat=category;app.database.execute(()->{try{File file=DiskMedia.importAudio(this,uri);String title="导入的音频";try(android.database.Cursor c=getContentResolver().query(uri,new String[]{android.provider.OpenableColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst())title=c.getString(0);}app.store.track(UUID.randomUUID().toString(),title,cat,file.getAbsolutePath(),true);app.changed();}catch(Exception e){app.main.post(()->toast(e.getMessage()==null?"导入失败":e.getMessage()));}});}}
    private interface Action{void run()throws Exception;}
    private void work(Action action,String success){app.database.execute(()->{try{action.run();app.changed();SyncService.schedule(this);app.main.post(()->toast(success));}catch(Exception e){app.main.post(()->toast(e instanceof IllegalArgumentException?e.getMessage():"操作未完成，请重试；原数据已保留"));}});}
    private void share(String text){startActivity(Intent.createChooser(new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,text),"分享照护交接"));}
    private void toast(String text){Toast.makeText(this,text==null?"请重试":text,Toast.LENGTH_LONG).show();}
    private boolean large(){return getResources().getConfiguration().fontScale>=1.3f;}
    private View iconButton(String kind,String label,Runnable action){LinearLayout button=u.row();button.setGravity(Gravity.CENTER);button.setPadding(u.dp(10),u.dp(6),u.dp(10),u.dp(6));button.setMinimumHeight(u.dp(52));button.setBackground(u.shape(u.soft,12));button.addView(u.assetIcon(kind,28));TextView text=u.text(label,14,u.green,true);text.setGravity(Gravity.CENTER);button.addView(text,new LinearLayout.LayoutParams(0,-2,1));button.setContentDescription(label);button.setClickable(true);button.setFocusable(true);button.setOnClickListener(v->action.run());return button;}
    private void addWeighted(LinearLayout parent,View v){LinearLayout.LayoutParams p=parent.getOrientation()==LinearLayout.VERTICAL?new LinearLayout.LayoutParams(-1,-2):new LinearLayout.LayoutParams(0,-2,1);p.setMargins(u.dp(2),0,u.dp(2),0);parent.addView(v,p);}
    private String time(long ms){if(ms==0)return "时间未知";return Instant.ofEpochMilli(ms).atZone(zone).format(DateTimeFormatter.ofPattern("HH:mm"));}
    private String datetime(long ms){if(ms==0)return "时间未知";return Instant.ofEpochMilli(ms).atZone(zone).format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));}
    private static String duration(long ms){long min=Math.max(0,ms/60000);return min>=60?min/60+"小时"+min%60+"分":min+"分钟";}
    private static String kindName(String kind){switch(kind){case "feeding":return "喂养";case "sleep":return "睡眠";case "diaper":return "尿布";case "bath":return "洗澡";case "tummy":return "趴玩";case "note":return "照护记录";default:return "计时";}}
    private String eventTitle(JSONObject e){return kindName(e.optString("kind"));}
    private String eventDetail(JSONObject e){String kind=e.optString("kind");if("feeding".equals(kind))return (e.optDouble("amount",0)==0?"数量未知":CareRules.quantity(e.optDouble("amount"))+" ml")+" · "+e.optString("detail");if("diaper".equals(kind))return e.optString("detail");if("sleep".equals(kind)&&e.optLong("end")==0&&e.optInt("active")==0)return "历史睡眠 · "+duration(e.optLong("duration"))+" · 起止未知";if("sleep".equals(kind))return e.optLong("end")==0?"进行中 · "+duration(System.currentTimeMillis()-e.optLong("start")):time(e.optLong("start"))+" — "+time(e.optLong("end"))+" · "+duration(e.optLong("end")-e.optLong("start"));return e.optLong("end")>0?duration(e.optLong("end")-e.optLong("start")):"已记录";}
    private static String requestStatus(String state){switch(state){case "completed":return "回复已保存";case "cancelled":return "请求已取消";case "failed":return "未能完成，可以重试";case "running":return "正在生成，可取消或离开页面";default:return "待发送 / 查询中";}}
}
