package cn.xigua.childcare;
import android.content.Context;
import android.util.Base64;
import android.util.Base64OutputStream;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;

/** Frozen user-selected compatible provider; credentials and waveforms never enter logs. */
final class MimoClient implements SpeechBackend {
    interface Progress {void update(String value);}
    private final JSONObject config;private final AtomicBoolean cancelled=new AtomicBoolean();private volatile HttpURLConnection connection;
    MimoClient(Context context,Store store)throws IOException{this(context,store,"chat");}
    MimoClient(Context context,Store store,String role)throws IOException{this(new Providers(context,store).resolve(role));}
    MimoClient(JSONObject snapshot){config=Providers.snapshot(snapshot);}
    public void ready()throws IOException{try{ProviderRules.validate(config.optString("name"),config.optString("base"),config.optString("key"),config.optString("chat_model"),config.optString("asr_model"),config.optString("auth","bearer"));}catch(IllegalArgumentException e){throw new IOException(e.getMessage());}if(config.optString("key").isEmpty())throw new IOException("请在AI服务中填写这套服务的API Key");}
    public void cancel(){cancelled.set(true);HttpURLConnection c=connection;if(c!=null)c.disconnect();}
    private void check()throws IOException{if(cancelled.get())throw new IOException("已取消");}
    private HttpURLConnection open(String path,String method)throws IOException{ready();check();HttpURLConnection c=(HttpURLConnection)new URL(config.optString("base").replaceAll("/+$","")+path).openConnection();connection=c;c.setInstanceFollowRedirects(false);c.setConnectTimeout(10000);c.setReadTimeout(60000);c.setRequestMethod(method);if("api-key".equals(config.optString("auth")))c.setRequestProperty("api-key",config.optString("key"));else c.setRequestProperty("Authorization","Bearer "+config.optString("key"));if(!"GET".equals(method)){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");}check();return c;}
    private JSONObject response(HttpURLConnection c)throws IOException,JSONException{check();int status=c.getResponseCode();if(status<200||status>=300)throw new IOException(status==401||status==403?"服务鉴权失败，请检查这套Key与URL是否匹配":status==429?"服务暂时限流，可稍后重试":status==404?"这套服务没有提供该接口，可手动填写模型或切换服务":"服务请求失败（"+status+"），可重试或切换服务");if(c.getContentLengthLong()>1024*1024)throw new IOException("回复超过大小上限");try(InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1){check();if(out.size()+n>1024*1024)throw new IOException("回复超过大小上限");out.write(buffer,0,n);}check();return new JSONObject(out.toString("UTF-8"));}}
    private String text(JSONObject json,boolean transcription)throws IOException{Object value=null;if(transcription)value=json.opt("text");else{JSONArray choices=json.optJSONArray("choices");JSONObject choice=choices==null?null:choices.optJSONObject(0),message=choice==null?null:choice.optJSONObject("message");if(message!=null)value=message.opt("content");}if(!(value instanceof String)||((String)value).trim().isEmpty())throw new IOException(transcription?"没有识别到文字，录音已保留，可重试":"模型没有返回文字，请检查模型或重试");String result=((String)value).trim();if(result.length()>12000)throw new IOException("文字较多，请分次处理；录音可重试");return result;}
    String chat(String prompt,boolean story)throws Exception{if(prompt.length()>12000)throw new IOException("输入最多12000字");JSONArray messages=new JSONArray().put(Store.obj("role","system","content",story?"用中文讲一个温柔、适合亲子共读的短故事。不要声称已经操作设备或保存记录。":"你是家庭照护助手，用中文简明回答。对医疗问题说明需要专业判断；不要声称已经操作设备或保存记录。")).put(Store.obj("role","user","content",prompt));JSONObject request=Store.obj("model",config.optString("chat_model"),"messages",messages,"stream",false);if(config.optString("base").contains("xiaomimimo.com")){request.put("thinking",Store.obj("type","disabled"));request.put("max_completion_tokens",2048);}else request.put("max_tokens",2048);byte[] data=request.toString().getBytes(StandardCharsets.UTF_8);HttpURLConnection c=open("/chat/completions","POST");try{c.setFixedLengthStreamingMode(data.length);try(OutputStream out=c.getOutputStream()){check();out.write(data);}return text(response(c),false);}finally{connection=null;c.disconnect();}}
    JSONArray models()throws Exception{HttpURLConnection c=open("/models","GET");try{JSONArray data=response(c).optJSONArray("data");if(data==null)throw new IOException("模型列表格式不兼容，仍可手动填写模型ID");Set<String> ids=new LinkedHashSet<>();for(int i=0;i<data.length()&&ids.size()<512;i++){JSONObject model=data.optJSONObject(i);if(model==null)continue;String id=model.optString("id").trim();if(!id.isEmpty()&&id.length()<=200&&id.indexOf('\n')<0&&id.indexOf('\r')<0)ids.add(id);}if(ids.isEmpty())throw new IOException("接口未返回模型，仍可手动填写模型ID");JSONArray list=new JSONArray();for(String id:ids)list.put(id);return list;}finally{connection=null;c.disconnect();}}
    public String transcribe(File wav,File scratch,Progress progress)throws Exception{long size=SpeechAudio.payloadBytes(wav);if(size<1600)throw new IOException("录音太短，请重新说一句");StringBuilder full=new StringBuilder();long offset=0;int total=(int)((size+SpeechAudio.CHUNK_BYTES-1)/SpeechAudio.CHUNK_BYTES),part=0;try{while(offset<size){check();long bytes=SpeechAudio.writeChunk(wav,offset,scratch);check();progress.update(total==1?"正在转成文字…":"正在转成文字 · "+(++part)+" / "+total);String segment=transcribePart(scratch);if(full.length()+segment.length()+1>12000)throw new IOException("文字较多，请分次发送；录音已保留");if(full.length()>0)full.append('\n');full.append(segment);offset+=bytes;scratch.delete();}check();return full.toString();}finally{scratch.delete();}}
    private String transcribePart(File wav)throws Exception{boolean multipart="transcriptions".equals(config.optString("asr_protocol"));String prefix,suffix,boundary="xigua-"+UUID.randomUUID();if(multipart){prefix="--"+boundary+"\r\nContent-Disposition: form-data; name=\"model\"\r\n\r\n"+config.optString("asr_model")+"\r\n--"+boundary+"\r\nContent-Disposition: form-data; name=\"file\"; filename=\"speech.wav\"\r\nContent-Type: audio/wav\r\n\r\n";suffix="\r\n--"+boundary+"--\r\n";}else{prefix="{\"model\":"+JSONObject.quote(config.optString("asr_model"))+",\"messages\":[{\"role\":\"user\",\"content\":[{\"type\":\"input_audio\",\"input_audio\":{\"data\":\"data:audio/wav;base64,";suffix="\",\"format\":\"wav\"}}]}],\"asr_options\":{\"language\":\"zh\"},\"stream\":false}";}byte[] head=prefix.getBytes(StandardCharsets.UTF_8),tail=suffix.getBytes(StandardCharsets.UTF_8);HttpURLConnection c=open(multipart?"/audio/transcriptions":"/chat/completions","POST");try{if(multipart)c.setRequestProperty("Content-Type","multipart/form-data; boundary="+boundary);c.setFixedLengthStreamingMode(head.length+(multipart?wav.length():4*((wav.length()+2)/3))+tail.length);try(OutputStream out=c.getOutputStream();InputStream in=new FileInputStream(wav)){out.write(head);OutputStream encoded=multipart?out:new Base64OutputStream(out,Base64.NO_WRAP|Base64.NO_CLOSE);byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1){check();encoded.write(buffer,0,n);}if(!multipart)encoded.close();out.write(tail);}return text(response(c),multipart);}finally{connection=null;c.disconnect();}}
}
