package cn.xigua.childcare;
import android.content.Context;
import org.json.*;
import java.io.*;
import java.util.*;

/** Persisted user profiles and two role bindings; an operation receives an immutable JSON copy. */
final class Providers {
 static final String[] ROLES={"chat","asr","tts","vision","judge"};
 static String modelKey(String role){return "asr".equals(role)?"asr_model":"tts".equals(role)?"tts_model":"vision".equals(role)?"vision_model":"judge".equals(role)?"judge_model":"chat_model";}
 static String roleLabel(String role){return "asr".equals(role)?"语音识别":"tts".equals(role)?"语音合成":"vision".equals(role)?"视觉理解":"judge".equals(role)?"JEV 判断":"文字推理";}
 private final Context context;private final Store store;
 Providers(Context context,Store store){this.context=context;this.store=store;}
 synchronized JSONArray all(){synchronized(store){String saved=store.get("providers","");if(!saved.isEmpty())try{return new JSONArray(saved);}catch(JSONException e){throw new IllegalStateException("服务配置无法读取，原配置已保留");}
  try(InputStream in=context.getAssets().open("mimo-config.json");ByteArrayOutputStream bytes=new ByteArrayOutputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1){if(bytes.size()+n>131072)throw new IOException();bytes.write(b,0,n);}JSONObject defaults=new JSONObject(bytes.toString("UTF-8"));JSONArray profiles=defaults.optJSONArray("providers");if(profiles==null)profiles=new JSONArray().put(defaults);
   for(int i=0;i<profiles.length();i++){JSONObject p=profiles.optJSONObject(i);if(p!=null){try{if(!p.has("tts_model"))p.put("tts_model","system");if(!p.has("vision_model"))p.put("vision_model","");if(!p.has("judge_model"))p.put("judge_model","");}catch(JSONException e){throw new IllegalStateException(e);}}}
   String legacy=store.get("mimo_key","");if(!legacy.isEmpty()){JSONObject p=Store.obj("id","legacy","name","原有服务","base",store.get("mimo_base",defaults.optString("base")),"key",legacy,"chat_model",defaults.optString("chat_model","mimo-v2.6-flash"),"asr_model",defaults.optString("asr_model","mimo-v2.5-asr"),"tts_model","system","vision_model","","judge_model","","auth","api-key","revision",1);profiles.put(p);store.set("provider_chat","legacy");store.set("provider_asr","legacy");}
   if(store.get("update_channel","__missing__").equals("__missing__"))store.set("update_channel",defaults.optString("update_channel",""));store.set("providers",profiles.toString());return profiles;
  }catch(Exception e){throw new IllegalStateException("内置服务配置无法读取");}
 }}
 JSONObject get(String id){JSONArray list=all();for(int i=0;i<list.length();i++){JSONObject p=list.optJSONObject(i);if(p!=null&&id.equals(p.optString("id")))return Store.json(p.toString());}return null;}
 String selected(String role){JSONArray list=all();return store.get("provider_"+role,list.length()==0?"":list.optJSONObject(0).optString("id"));}
 boolean configured(String role){String id=selected(role);JSONObject p=get(id);if(p==null)return false;String model=p.optString(modelKey(role));return "tts".equals(role)&&"system".equals(model)||!model.isEmpty()&&!p.optString("key").isEmpty();}
 JSONObject resolve(String role)throws IOException{if(!java.util.Arrays.asList(ROLES).contains(role))throw new IOException("未知模型角色");JSONObject p=get(selected(role));if(p==null)throw new IOException("请先选择"+roleLabel(role)+"服务");try{validate(p);}catch(IllegalArgumentException e){throw new IOException(e.getMessage());}String model=p.optString(modelKey(role));if(!("tts".equals(role)&&"system".equals(model))&&p.optString("key").isEmpty())throw new IOException("这套服务尚未填写API Key，请在AI服务中完善");if(model.isEmpty())throw new IOException("请在AI服务中选择"+roleLabel(role)+"模型");return p;}
 private static void validate(JSONObject p){ProviderRules.validate(p.optString("name"),p.optString("base"),p.optString("key"),p.optString("chat_model"),p.optString("asr_model"),p.optString("auth","bearer"));for(String role:ROLES){String model=p.optString(modelKey(role));if(model.length()>200||model.indexOf('\n')>=0||model.indexOf('\r')>=0)throw new IllegalArgumentException("模型ID最多200字");}if(!java.util.Arrays.asList("mimo","transcriptions").contains(p.optString("asr_protocol","mimo")))throw new IllegalArgumentException("请选择识别接口");}
 void save(JSONObject draft){validate(draft);synchronized(store){JSONArray list=all(),next=new JSONArray();String id=draft.optString("id");if(id.isEmpty())id=UUID.randomUUID().toString();boolean found=false;for(int i=0;i<list.length();i++){JSONObject old=list.optJSONObject(i);if(id.equals(old.optString("id"))){found=true;if(draft.optLong("revision")!=old.optLong("revision"))throw new IllegalArgumentException("配置已变化，请重新打开编辑");draft=Store.json(draft.toString());try{draft.put("revision",old.optLong("revision")+1);}catch(JSONException e){throw new IllegalArgumentException(e);}next.put(draft);}else next.put(old);}
   if(!found){if(list.length()>=20)throw new IllegalArgumentException("最多保存20套服务");draft=Store.json(draft.toString());try{draft.put("id",id);draft.put("revision",1);}catch(JSONException e){throw new IllegalArgumentException(e);}next.put(draft);}persist(next);
 }}
 void select(String role,String id){synchronized(store){JSONObject p=get(id);if(p==null)throw new IllegalArgumentException("服务已不存在");validate(p);String model=p.optString(modelKey(role));if(!("tts".equals(role)&&"system".equals(model))&&(p.optString("key").isEmpty()||model.isEmpty()))throw new IllegalArgumentException("请先填写密钥及模型");store.set("provider_"+role,id);}}
 void delete(String id){synchronized(store){JSONArray list=all(),next=new JSONArray();for(int i=0;i<list.length();i++)if(!id.equals(list.optJSONObject(i).optString("id")))next.put(list.optJSONObject(i));persist(next);for(String role:ROLES)if(id.equals(selected(role)))store.set("provider_"+role,next.length()==0?"":next.optJSONObject(0).optString("id"));}}
 boolean models(String id,long revision,JSONArray models,String status){synchronized(store){JSONObject current=get(id);if(current==null||current.optLong("revision")!=revision)return false;JSONArray list=all(),next=new JSONArray();for(int i=0;i<list.length();i++){JSONObject p=list.optJSONObject(i);if(id.equals(p.optString("id")))try{p.put("models",models);p.put("models_status",status);}catch(JSONException e){throw new IllegalArgumentException(e);}next.put(p);}persist(next);return true;}}
 static JSONObject snapshot(JSONObject p){return Store.obj("id",p.optString("id"),"name",p.optString("name"),"base",p.optString("base"),"key",p.optString("key"),"chat_model",p.optString("chat_model"),"asr_model",p.optString("asr_model"),"tts_model",p.optString("tts_model"),"vision_model",p.optString("vision_model"),"judge_model",p.optString("judge_model"),"auth",p.optString("auth","bearer"),"asr_protocol",p.optString("asr_protocol","mimo"),"revision",p.optLong("revision"));}
 private void persist(JSONArray list){String text=list.toString();if(text.length()>2*1024*1024)throw new IllegalArgumentException("模型缓存较大，请清理不需要的服务");store.set("providers",text);}
}
