package cn.xigua.childcare;
import android.content.*;
import android.content.pm.*;
import android.net.Uri;
import android.os.Build;
import org.json.*;
import java.io.*;
import java.net.*;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;

/** Private cloud channel, frozen request ownership and exact package/signer continuity. */
final class Updates {
    interface Transport {HttpURLConnection open(String url)throws IOException;}
    static Transport transport=url->(HttpURLConnection)new URL(url).openConnection();
    static final class Channel {final String url,token,fallback,fallbackToken;final long epoch;Channel(String u,String t,String f,String ft,long e){url=u;token=t;fallback=f;fallbackToken=ft;epoch=e;}}
    static Channel channel(Store s){synchronized(s){return new Channel(s.get("update_channel",""),s.get("update_token",""),s.get("update_fallback",""),s.get("update_fallback_token",s.get("update_token","")),epoch(s));}}
    private static long epoch(Store s){try{return Long.parseLong(s.get("update_epoch","0"));}catch(Exception e){return 0;}}
    static boolean owns(Store s,Channel c){Channel now=channel(s);return c.url.equals(now.url)&&c.token.equals(now.token)&&c.fallback.equals(now.fallback)&&c.fallbackToken.equals(now.fallbackToken)&&c.epoch==now.epoch;}
    static void initialize(CareApp app){try(InputStream in=app.getAssets().open("update-config.json");ByteArrayOutputStream bytes=new ByteArrayOutputStream()){byte[] b=new byte[1024];int n;while((n=in.read(b))!=-1){if(bytes.size()+n>16384)throw new IOException("更新配置过大");bytes.write(b,0,n);}JSONObject cfg=new JSONObject(bytes.toString("UTF-8"));String primary=cfg.getString("manifest_url"),legacy=cfg.optString("legacy_manifest_url","");synchronized(app.store){boolean custom="1".equals(app.store.get("update_custom","0"));String existing=app.store.get("update_channel","");if(!custom&&(existing.isEmpty()||existing.equals(legacy))){configureWithFallback(app.store,primary,cfg.getString("download_token"),legacy,false);app.store.set("update_fallback_token",cfg.optString("legacy_download_token",cfg.getString("download_token")));}else if(!custom&&!legacy.isEmpty()&&app.store.get("update_fallback","").isEmpty()){app.store.set("update_fallback",legacy);app.store.set("update_fallback_token",cfg.optString("legacy_download_token",cfg.getString("download_token")));}if(app.store.get("update_automatic","__missing__").equals("__missing__"))app.store.set("update_automatic","1");}}catch(Exception e){app.store.set("update_status","更新频道配置不可用，其他功能可继续使用");}}
    static void maybeCheck(CareApp app){if(!"1".equals(app.store.get("update_automatic","1"))||channel(app.store).url.isEmpty())return;long last;try{last=Long.parseLong(app.store.get("update_last_attempt","0"));}catch(Exception e){last=0;}long elapsed=System.currentTimeMillis()-last;if(elapsed>=0&&elapsed<6*3600000L)return;if(!queued.compareAndSet(false,true))return;try{app.network.execute(()->{try{checkChannel(app);}finally{queued.set(false);}});}catch(RuntimeException e){queued.set(false);throw e;}}
    static final long LIMIT=64L*1024*1024;static final AtomicBoolean busy=new AtomicBoolean(),queued=new AtomicBoolean();private static volatile HttpURLConnection connection;private static volatile boolean cancelled;
    static long version(PackageInfo info){return Build.VERSION.SDK_INT>=28?info.getLongVersionCode():info.versionCode;}
    static PackageInfo installed(Context c)throws PackageManager.NameNotFoundException{return c.getPackageManager().getPackageInfo(c.getPackageName(),Build.VERSION.SDK_INT>=28?PackageManager.GET_SIGNING_CERTIFICATES:PackageManager.GET_SIGNATURES);}
    static File dir(Context c){File d=new File(c.getCacheDir(),"updates");if(!d.isDirectory()&&!d.mkdirs())throw new IllegalStateException("更新暂存目录不可写");return d;}
    static void cleanup(Context c){File[] files=dir(c).listFiles();if(files!=null)for(File f:files)if(f.getName().endsWith(".part"))f.delete();if(c.getApplicationContext() instanceof CareApp){CareApp app=(CareApp)c.getApplicationContext();try{JSONObject candidate=Store.json(app.store.get("update_candidate","{}"));if(candidate.optLong("version_code",Long.MAX_VALUE)<=version(installed(c))){if(files!=null)for(File f:files)if(f.getName().matches("candidate-[0-9]+-[a-f0-9]{12}\\.apk"))f.delete();app.store.set("update_file","");app.store.set("update_candidate","");app.store.set("update_release","");app.store.set("update_status","已更新到 "+installed(c).versionName);}}catch(Exception ignored){}}}
    static void cancel(CareApp app){cancelled=true;HttpURLConnection c=connection;if(c!=null)c.disconnect();app.store.set("update_status","正在取消更新准备");app.changed();}
    private static void check()throws IOException{if(cancelled)throw new IOException("更新准备已取消");}
    private static void status(CareApp app,String value){app.store.set("update_status",value);app.changed();}
    private static boolean begin(CareApp app){if(!busy.compareAndSet(false,true))return false;cancelled=false;status(app,"正在准备，请稍候");return true;}
    private static HttpURLConnection open(String url,String token)throws IOException{UpdateRules.https(url);UpdateRules.token(token);HttpURLConnection c=transport.open(url);connection=c;c.setInstanceFollowRedirects(false);c.setConnectTimeout(10000);c.setReadTimeout(30000);c.setRequestProperty("Cache-Control","no-cache");if(!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);int code=c.getResponseCode();if(code!=200){c.disconnect();throw new IOException(code==401||code==403?"更新频道验证未通过，请联系维护者":code==404?"更新频道尚未发布版本，请稍后检查":"更新服务器不可用，请稍后重试");}return c;}
    static void configure(Store store,String value,String token,boolean custom){configureWithFallback(store,value,token,"",custom);}
static void configureWithFallback(Store store,String value,String token,String fallback,boolean custom){if(!value.isEmpty())UpdateRules.https(value);if(!fallback.isEmpty())UpdateRules.https(fallback);UpdateRules.token(token);synchronized(store){android.database.sqlite.SQLiteDatabase db=store.getWritableDatabase();db.beginTransaction();try{long epoch=channel(store).epoch;store.set("update_channel",value);store.set("update_token",token);store.set("update_fallback",fallback);store.set("update_fallback_token",fallback.isEmpty()?"":token);store.set("update_epoch",String.valueOf(epoch+1));store.set("update_custom",custom?"1":"0");store.set("update_release","");store.set("update_file","");store.set("update_candidate","");store.set("update_source","");store.set("update_last_attempt","0");store.set("update_last_checked","0");store.set("update_status",value.isEmpty()?"在线更新已关闭":"已接入独立更新频道");db.setTransactionSuccessful();}finally{db.endTransaction();}}}
    static void setChannel(Store store,String value){configure(store,value,"",true);}
    private static void owned(CareApp app,Channel owner)throws IOException{check();if(!owns(app.store,owner))throw new IOException("更新频道已变化，请重新检查");}
    private static void releaseStatus(CareApp app,Channel owner,String value){synchronized(app.store){if(owns(app.store,owner))status(app,value);}}
    private static JSONObject loadRelease(CareApp app,Channel owner,String manifest,String token)throws Exception{HttpURLConnection c=null;try{owned(app,owner);c=open(manifest,token);if(c.getContentLengthLong()>65536)throw new IOException("更新清单过大");ByteArrayOutputStream out=new ByteArrayOutputStream();try(InputStream in=c.getInputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1){owned(app,owner);if(out.size()+n>65536)throw new IOException("更新清单过大");out.write(b,0,n);}}owned(app,owner);JSONObject release=new JSONObject(out.toString("UTF-8"));PackageInfo current=installed(app);UpdateRules.validate(release.getString("package_name"),release.getLong("version_code"),release.getInt("min_sdk"),release.getString("apk_url"),release.getString("sha256"),app.getPackageName(),0,Build.VERSION.SDK_INT);UpdateRules.sameOrigin(manifest,release.getString("apk_url"));if(release.optString("version_name").isEmpty()||release.optString("version_name").length()>64||release.optString("notes").length()>8000)throw new IOException("版本清单内容无效");return release;}finally{if(c!=null)c.disconnect();}}
    static void checkChannel(CareApp app){if(!begin(app))return;Channel owner=channel(app.store);try{if(owner.url.isEmpty())throw new IOException("尚未接入更新频道");app.store.set("update_last_attempt",String.valueOf(System.currentTimeMillis()));JSONObject release;String source;try{release=loadRelease(app,owner,owner.url,owner.token);source="primary";}catch(Exception primary){if(owner.fallback.isEmpty()||owner.fallback.equals(owner.url))throw primary;status(app,"主更新频道暂不可用，正在尝试兼容频道");release=loadRelease(app,owner,owner.fallback,owner.fallbackToken);source="legacy";}synchronized(app.store){owned(app,owner);app.store.set("update_source",source);if(release.getLong("version_code")<=version(installed(app))){app.store.set("update_release","");status(app,"已是最新版本 "+installed(app).versionName);}else{app.store.set("update_release",release.toString());status(app,"发现新版本 "+release.optString("version_name"));}app.store.set("update_last_checked",String.valueOf(System.currentTimeMillis()));}}catch(Exception e){synchronized(app.store){if(owns(app.store,owner)){app.store.set("update_release","");status(app,error(e));}}}finally{connection=null;busy.set(false);app.changed();}}
    static void download(CareApp app){if(!begin(app))return;Channel owner=channel(app.store);HttpURLConnection c=null;File part=null;try{part=new File(dir(app),"download.part");JSONObject r=Store.json(app.store.get("update_release",""));PackageInfo current=installed(app);UpdateRules.validate(r.getString("package_name"),r.getLong("version_code"),r.getInt("min_sdk"),r.getString("apk_url"),r.getString("sha256"),app.getPackageName(),version(current),Build.VERSION.SDK_INT);UpdateRules.sameOrigin("legacy".equals(app.store.get("update_source","primary"))?owner.fallback:owner.url,r.getString("apk_url"));String downloadToken="legacy".equals(app.store.get("update_source","primary"))?owner.fallbackToken:owner.token;c=open(r.getString("apk_url"),downloadToken);if(c.getContentLengthLong()>LIMIT)throw new IOException("安装包超过64MiB上限");try(InputStream in=c.getInputStream()){copy(in,part);}owned(app,owner);if(!hash(part).equalsIgnoreCase(r.getString("sha256")))throw new IOException("安装包校验失败，未进入安装流程");PackageInfo candidate=verify(app,part);if(version(candidate)!=r.getLong("version_code")||candidate.applicationInfo.minSdkVersion!=r.getInt("min_sdk")||!candidate.versionName.equals(r.getString("version_name")))throw new IOException("安装包版本与频道不符");synchronized(app.store){owned(app,owner);stage(app,part,candidate);}}catch(Exception e){releaseStatus(app,owner,error(e));}finally{if(part!=null)part.delete();if(c!=null)c.disconnect();connection=null;busy.set(false);app.changed();}}
    static void importApk(CareApp app,Uri uri){if(!begin(app))return;File part=null;try{part=new File(dir(app),"import.part");try(InputStream in=app.getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("无法读取安装包");copy(in,part);stage(app,part,verify(app,part));}}catch(Exception e){status(app,error(e));}finally{if(part!=null)part.delete();busy.set(false);app.changed();}}
    private static void copy(InputStream in,File file)throws IOException{if(file.getParentFile().getUsableSpace()<4*1024*1024)throw new IOException("手机可用空间不足");try(OutputStream out=new FileOutputStream(file)){byte[] buffer=new byte[32768];long total=0;int n;while((n=in.read(buffer))!=-1){check();total+=n;if(total>LIMIT)throw new IOException("安装包超过64MiB上限");if(file.getParentFile().getUsableSpace()<2*1024*1024)throw new IOException("手机可用空间不足");out.write(buffer,0,n);}if(total==0)throw new IOException("安装包为空");}}
    static String hash(File file)throws Exception{MessageDigest digest=MessageDigest.getInstance("SHA-256");try(InputStream in=new FileInputStream(file)){byte[] b=new byte[32768];int n;while((n=in.read(b))!=-1)digest.update(b,0,n);}StringBuilder text=new StringBuilder();for(byte b:digest.digest())text.append(String.format(Locale.ROOT,"%02x",b&255));return text.toString();}
    private static List<String> signers(PackageInfo p)throws Exception{Signature[] signatures=Build.VERSION.SDK_INT>=28?(p.signingInfo==null?null:p.signingInfo.getApkContentsSigners()):p.signatures;if(signatures==null||signatures.length==0)throw new IOException("安装包没有可验证签名");List<String> values=new ArrayList<>();for(Signature s:signatures)values.add(android.util.Base64.encodeToString(MessageDigest.getInstance("SHA-256").digest(s.toByteArray()),android.util.Base64.NO_WRAP));Collections.sort(values);return values;}
    static PackageInfo verify(Context c,File file)throws Exception{if(file.length()<1||file.length()>LIMIT)throw new IOException("安装包大小无效");PackageInfo candidate=c.getPackageManager().getPackageArchiveInfo(file.getAbsolutePath(),Build.VERSION.SDK_INT>=28?PackageManager.GET_SIGNING_CERTIFICATES:PackageManager.GET_SIGNATURES);if(candidate==null)throw new IOException("无法识别有效的APK");PackageInfo current=installed(c);if(!c.getPackageName().equals(candidate.packageName))throw new IOException("这个APK不属于西瓜育儿");if(version(candidate)<=version(current))throw new IOException("只允许升级到更新版本，当前数据已保留");if(candidate.applicationInfo==null||candidate.applicationInfo.minSdkVersion>Build.VERSION.SDK_INT)throw new IOException("安装包需要更新的Android系统");if(!signers(current).equals(signers(candidate)))throw new IOException("安装包签名不匹配，不能覆盖当前应用");return candidate;}
    private static void stage(CareApp app,File part,PackageInfo candidate)throws Exception{check();String digest=hash(part);check();File dst=new File(dir(app),"candidate-"+version(candidate)+"-"+digest.substring(0,12)+".apk");if(dst.exists())dst.delete();if(!part.renameTo(dst))throw new IOException("无法保存更新包");File[] files=dir(app).listFiles();if(files!=null)for(File f:files)if(f.getName().startsWith("candidate-")&&!f.equals(dst))f.delete();app.store.set("update_file",dst.getName());app.store.set("update_candidate",Store.obj("version_name",candidate.versionName,"version_code",version(candidate),"sha256",digest).toString());status(app,"安装包已校验，等待你确认安装");}
    static void install(android.app.Activity a)throws Exception{CareApp app=(CareApp)a.getApplication();String name=app.store.get("update_file","");if(!name.matches("candidate-[0-9]+-[a-f0-9]{12}\\.apk"))throw new IOException("请先选择或下载更新包");File file=new File(dir(a),name);JSONObject staged=Store.json(app.store.get("update_candidate","{}"));if(!hash(file).equalsIgnoreCase(staged.optString("sha256")))throw new IOException("暂存安装包已变化，请重新下载");verify(a,file);if(!a.getPackageManager().canRequestPackageInstalls()){a.startActivity(new Intent(android.provider.Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+a.getPackageName())));return;}Uri uri=Uri.parse("content://"+a.getPackageName()+".updates/"+name);a.startActivity(new Intent(Intent.ACTION_VIEW).setDataAndType(uri,"application/vnd.android.package-archive").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION));}
    private static String error(Exception e){return e instanceof IOException||e instanceof IllegalArgumentException?e.getMessage():"更新准备未完成，请检查频道或安装包后重试";}
}
